targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          create_factory: true
          create_to_json: true
          checked: true
      retrofit_generator:
        options:
          ignore_unsupported_warnings: true
