import '../constants/text_strings.dart';

class Arabic {
  Arabic._();

  static Map<String, String> ar = {
    /// Global Texts
    FTexts.appName: 'فاحص',
    FTexts.cancelBtn: 'إلغاء',
    FTexts.skip: 'تخطي',
    FTexts.refresh: 'جرب مره ثانيه',
    FTexts.submitBtn: 'إرسال',
    FTexts.nextBtn: 'التالي',
    FTexts.backBtn: 'السابق',
    FTexts.requestId: 'رقم الطلب',
    FTexts.deleteBtn: 'حذف',
    FTexts.signOut: 'تسجيل الخروج',
    FTexts.updateAssets: 'تحديث الموارد',
    FTexts.offlineMode: 'وضع عدم الاتصال',
    'All': 'الكل',
    'sessionExpired': 'انتهت الجلسة',
    'sessionExpiredMsg': 'تم تسجيل الدخول من جهاز آخر. يرجى إعادة الدخول.',
    'fieldRequired': 'هذا الحقل مطلوب.',
    'vinMustBe17': 'رقم الهيكل يجب أن يكون 17 حرف .',
    'ccNumbersOnly': 'يسمح فقط بالأرقام.',
    'colorNoNumbers': 'اللون لا يمكن أن يحتوي على أرقام.',
    'milageNumbersOnly': 'يجب أن يكون رقمًا.',
    'Pending': 'معلقة',
    'Accepted': 'مقبولة',
    'In Progress': 'جاري فحصها',
    'Finished': 'منتهية',
    'Rejected': 'مرفوضة',
    'Reviewed': 'تمت مراجعتها',
    'Settings & Support': 'الإعدادات و الدعم',
    'Help & Support': 'الإعدادات و الدعم',

    /// End Global Texts
    ///
    /// Enums Texts
    FTexts.automatic: 'اوتوماتيك',
    FTexts.manual: 'عادي',
    FTexts.fabric: 'قماش',
    FTexts.leather: 'جلد',
    FTexts.inProgress: 'جاري الفحص',
    FTexts.pended: 'معلق',
    FTexts.approved: 'موثق',
    FTexts.finished: 'منتهي',
    FTexts.good: 'جيد',
    FTexts.notes: 'ملاحظة',
    FTexts.na: 'لا يوجد',
    FTexts.unSelected: 'غير محدد',
    ForgetPage.forgetSubTitle: 'ادخل رقم جوالك و راح نرسل لك رمز التحقق',
    FTexts.more: 'المزيد',

    /// End Enums Texts
    ///
    /// Login Page
    LoginPage.loginTitle: 'تطبيق مراكز الفحص',
    LoginPage.loginSubTitle: 'مرحباً بعودتك',
    LoginPage.phoneNumber: 'رقم الجوال',
    LoginPage.phoneNumberValidation: 'يجب ان يكون رقم جوال صحيح',
    LoginPage.username: 'البريد الإلكتروني او الجوال',
    LoginPage.emailValidation: 'يجب ان تكون كلمة المرور اكبر من 8 رموز',
    LoginPage.password: 'كلمة المرور',
    LoginPage.passwordValidation: 'لازم تدخل الباسورد عشان السريه و كذا',
    LoginPage.rememberMe: 'تذكرني',
    LoginPage.signIn: 'تسجيل الدخول',
    LoginPage.verifyOTP: 'تحقق',
    LoginPage.resetPassword: 'إعادة تعيين كلمة المرور',
    'resetPasswordSubtitle': 'أدخل كلمة المرور الجديدة أدناه.',
    'newPassword': 'كلمة المرور الجديدة',
    'confirmPassword': 'تأكيد كلمة المرور',
    'passwordMismatch': 'كلمتا المرور غير متطابقتين',
    LoginPage.forgetBTN: 'نسيت كلمة المرور؟',
    LoginPage.loginWithEmail: 'الدخول بأستخدام البريد الإلكتروني',
    LoginPage.otpTitle: 'رمز التحقق',
    LoginPage.resendBtnWithTime: 'إعادة الإرسال (بعد @s ث)',
    LoginPage.resendBtn: 'إعادة الإرسال',
    LoginPage.editPhoneNumber: 'تعدبل رقم الهاتف',
    LoginPage.processingTitle:
        '...يتم تسجيل الدخول و تجهيز البيانات (لن يستغرق سوا ثواني)',

    /// End Login Page
    ///
    /// Home Page
    HomePage.searchHint: 'البحث باستخدام رقم اللوحة....',
    HomePage.request: 'الطلبات',
    HomePage.searchPlaceholder: 'أبحث...',
    HomePage.history: 'سجل الطلبات',
    HomePage.onEmpty: 'onEmpty',
    HomePage.onError: 'There is an error occurred',
    HomePage.noMore: 'لا يوجد لديك طلبات حالياً',

    /// End Home Page
    ///
    /// Inspection Details Page
    InspectionPage.generalInfo: 'المعلومات العامة',
    InspectionPage.vehicleInfo: 'معلومات المركبة',
    InspectionPage.connectPersonInfo: 'معلومات التواصل',
    InspectionPage.inspectionPointReview: 'ملخص نقاط الفحص',
    InspectionPage.inspectionType: 'نوع الفحص',
    InspectionPage.center: 'مركز الفحص',
    InspectionPage.centerBranch: 'فرع مركز الفحص',
    InspectionPage.city: 'مدينة المركز',
    InspectionPage.bookingDate: 'تاريخ الحجز',
    InspectionPage.assignedTo: 'إسناد الفحص لـ',
    InspectionPage.inspector: 'أسم الفاحص',
    InspectionPage.inspectedAt: 'تاريخ الفحص',
    InspectionPage.reviewedAt: 'تاريخ المراجعة',
    InspectionPage.createdAt: 'تاريخ الإنشاء',
    InspectionPage.inspectorNote: 'ملاحظة الفاحص',
    InspectionPage.reviewerNote: 'ملاحظة المراجع',
    InspectionPage.notYet: 'لم يحدد بعد',
    InspectionPage.anyInspector: 'كل الفاحصين',
    InspectionPage.vin: 'رقم الهيكل',
    InspectionPage.serialNo: 'رقم بيانات المركبة',
    InspectionPage.make: 'الشركة المصنعة',
    InspectionPage.model: 'الموديل',
    InspectionPage.storageSize: 'حجم الصهريج',
    InspectionPage.vehicleShape: 'شكل صهريج',
    InspectionPage.yearModel: 'سنة الموديل',
    InspectionPage.plate: 'رقم اللوحة',
    InspectionPage.contactName: 'الاسم',
    InspectionPage.contactEmail: 'البريد الإلكتروني',
    InspectionPage.contactPhone: 'الجوال',
    InspectionPage.contactCity: 'المدينة',
    InspectionPage.inspectionPhotos: 'صور الفحص',
    InspectionPage.inspectionBodyNotes: 'ملاحظات هيكل المركبة',
    InspectionPage.inspectionOBDCodes: 'رموز OBD للفحص',
    InspectionPage.loadingInspectionDetails: 'جاري تحميل تفاصيل الفحص...',
    InspectionPage.noteLabel: 'ملاحظة @index',
    InspectionPage.positionLabel: 'الموقع: (@dx, @dy)',
    InspectionPage.notesCount: '@count ملاحظات',
    InspectionPage.pointsReview: 'مراجعة النقاط',
    InspectionPage.inspectionDetailsTitle: 'تفاصيل الفحص',
    InspectionPage.doneBtn: 'تم',
    InspectionPage.remaining: 'متبقية',
    InspectionPage.imageRequired: 'الصورة مطلوبة',
    InspectionPage.imageRequiredMsg: 'يجب توثيق الملاحظة بصورة توضح الحالة',
    InspectionPage.noteRequired: 'الملاحظة مطلوبة',
    InspectionPage.noteRequiredMsg: 'يجب وصف الحالة',
    InspectionPage.resetPointsTitle: 'إعادة تعيين النقاط',
    InspectionPage.resetPointsContent:
        'هل أنت متأكد من إعادة تعيين جميع النقاط؟ سيتم حذف جميع التغييرات على النقاط الحالية.',
    InspectionPage.resetPointsConfirm: 'إعادة تعيين',
    InspectionPage.selectStatus: 'اختر الحالة',
    InspectionPage.addNoteTitle: 'إضافة ملاحظة',
    InspectionPage.noteSavedSuccessMsg: 'تم حفظ الملاحظة بنجاح',
    InspectionPage.noteHint: 'اكتب ملاحظتك هنا...',
    InspectionPage.noteFieldLabel: 'الملاحظة',
    InspectionPage.noteValidation: 'الملاحظة مطلوبة',
    InspectionPage.photosTitle: 'الصور',
    InspectionPage.uploadedPhotos: 'تم الرفع',
    InspectionPage.availablePhotos: 'متاحة',
    InspectionPage.photoUploaded: 'تم الرفع',
    InspectionPage.addPhoto: 'إضافة صورة',
    InspectionPage.selectPhotoTitle: 'اختر الصورة لالتقاطها',
    InspectionPage.noPhotosYet: 'لا توجد صور بعد',
    InspectionPage.photosProgress: '@uploaded / @total صور',
    InspectionPage.takePhoto: 'التقاط صورة',
    InspectionPage.deletePhoto: 'حذف الصورة',
    InspectionPage.deletePhotoConfirm: 'هل أنت متأكد أنك تريد حذف هذه الصورة؟',
    InspectionPage.photoDeletedSuccess: 'تم حذف الصورة بنجاح.',
    InspectionPage.deleteAllPhotos: 'حذف جميع الصور',
    InspectionPage.deleteAllPhotosConfirm:
        'هل أنت متأكد؟ سيتم حذف جميع الصور المرفوعة وإعادة تعيينها.',
    InspectionPage.deleteAllPhotosSuccess: 'تم حذف جميع الصور بنجاح.',
    InspectionPage.deleteObdCode: 'حذف الكود',
    InspectionPage.deleteObdCodeConfirm: 'هل أنت متأكد أنك تريد حذف هذا الكود؟',
    InspectionPage.deleteBodyNote: 'حذف الملاحظة',
    InspectionPage.deleteBodyNoteConfirm:
        'هل أنت متأكد أنك تريد حذف هذه الملاحظة؟',
    InspectionPage.photoCategoryExterior: 'خارجية',
    InspectionPage.photoCategoryInterior: 'داخلية',
    InspectionPage.startInspection: 'ابدأ الفحص',
    InspectionPage.generalNoteTitle: 'إرسال الفحص',
    InspectionPage.rejectionNoteTitle: 'رفض الفحص',
    InspectionPage.noteOptionalHint: 'أضف ملاحظة (اختياري)...',
    InspectionPage.confirmSubmit: 'تأكيد',
    InspectionPage.cancelBtn: 'إلغاء',
    InspectionPage.submitConfirmSubtitle: 'هل أنت متأكد من إرسال هذا الفحص؟',
    InspectionPage.rejectConfirmSubtitle: 'هل أنت متأكد من رفض هذا الفحص؟',
    InspectionPage.addNoteLabel: 'إضافة ملاحظة',
    InspectionPage.optionalTag: 'اختياري',
    InspectionPage.obdFileName: 'تقرير OBD',
    InspectionPage.uploadObdReport: 'رفع تقرير OBD',
    InspectionPage.obdCodesTitle: 'أكواد OBD',
    InspectionPage.obdCodeRequired: 'الرمز مطلوب',
    InspectionPage.obdCodeRequiredMsg: 'يرجى إدخال رمز OBD',
    InspectionPage.obdDescRequired: 'الوصف مطلوب',
    InspectionPage.obdDescRequiredMsg: 'يرجى إدخال وصف الرمز',
    InspectionPage.obdDataRequired: 'بيانات OBD مطلوبة',
    InspectionPage.obdDataRequiredMsg:
        'يرجى رفع ملف التقرير أو إضافة رمز OBD واحد على الأقل قبل المتابعة',
    InspectionPage.obdFileTooLarge: 'حجم الملف كبير',
    InspectionPage.obdFileTooLargeMsg:
        'يجب أن يكون حجم الملف أقل من 1 ميجابايت',
    InspectionPage.obdUploadSuccess: 'تم رفع التقرير بنجاح',
    InspectionPage.obdUploadFailed: 'فشل رفع التقرير',
    InspectionPage.obdDeleteSuccess: 'تم حذف التقرير',
    InspectionPage.obdDeleteReportTitle: 'حذف التقرير',
    InspectionPage.obdDeleteReportConfirm:
        'هل أنت متأكد أنك تريد حذف تقرير OBD؟',
    InspectionPage.obdCodeDeletedSuccess: 'تم الحذف',
    InspectionPage.obdCodeDeletedSuccessMsg: 'تم حذف رمز OBD بنجاح',
    InspectionPage.obdCodeAddSuccess: 'تمت الإضافة',
    InspectionPage.obdCodeAddSuccessMsg: 'تمت إضافة رمز OBD بنجاح',
    InspectionPage.obdCodeEditSuccess: 'تم التعديل',
    InspectionPage.obdCodeEditSuccessMsg: 'تم تعديل رمز OBD بنجاح',
    InspectionPage.obdActionError: 'حدث خطأ، يرجى المحاولة مرة أخرى',
    InspectionPage.obdAddCode: 'إضافة رمز OBD',
    InspectionPage.obdEditCode: 'تعديل رمز OBD',
    InspectionPage.obdCodeLabel: 'رمز OBD',
    InspectionPage.obdCodeHint: 'مثال: P0300',
    InspectionPage.obdDescLabel: 'الوصف',
    InspectionPage.obdDescHint: 'وصف الرمز...',
    InspectionPage.obdNoCodesYet: 'لا توجد أكواد OBD بعد',
    InspectionPage.bodyNotesEmpty: 'لا توجد ملاحظات بعد',
    InspectionPage.obdReportSection: 'تقرير OBD',
    InspectionPage.obdOptionalBadge: 'اختياري',
    InspectionPage.obdConnectDevice: 'ربط الجهاز',
    InspectionPage.obdDisconnect: 'قطع الاتصال',
    InspectionPage.obdReadFromDevice: 'قراءة من الجهاز',
    InspectionPage.obdConnecting: 'جارٍ الاتصال…',
    InspectionPage.obdReadingCodes: 'جارٍ قراءة الأكواد…',
    InspectionPage.obdConnectionFailed: 'فشل الاتصال',
    InspectionPage.obdDeviceDisconnected: 'تم قطع الجهاز',
    InspectionPage.obdReconnect: 'إعادة الاتصال',
    InspectionPage.obdNoCodesFromDevice: 'لم يتم العثور على أكواد أعطال',
    InspectionPage.obdNoNewCodes: 'لا توجد أكواد جديدة من الجهاز',
    InspectionPage.obdCodesAdded: 'تمت إضافة @count كود من الجهاز',
    InspectionPage.obdScanTitle: 'اختر جهاز OBD',
    InspectionPage.obdBleNotSupported: 'البلوتوث غير مدعوم على هذا الجهاز',
    InspectionPage.obdBleOff: 'يرجى تشغيل البلوتوث',
    InspectionPage.obdBlePermissionDenied: 'يلزم إذن البلوتوث',
    InspectionPage.obdConnectedTo: 'متصل: @name',
    InspectionPage.obdAddManualCode: 'إضافة يدوياً',
    InspectionPage.obdScanStart: 'بحث عن الأجهزة',
    InspectionPage.obdScanStop: 'إيقاف البحث',
    InspectionPage.obdScanEmptyTitle: 'لم يتم العثور على أجهزة',
    InspectionPage.obdScanEmptyHint: 'اضغط على "بحث عن الأجهزة" للبدء',
    InspectionPage.obdScanScanningTitle: 'جارٍ البحث…',
    InspectionPage.obdScanScanningHint:
        'شغّل البلوتوث وضع جهاز Veepeak بالقرب منك للبحث',
    InspectionPage.obdScanSectionNamed: 'الأجهزة المتاحة',
    InspectionPage.obdScanUnknownDevice: 'جهاز غير معروف',
    InspectionPage.obdScanRecommended: 'موصى به',
    InspectionPage.obdFromDevice: 'من الجهاز',
    InspectionPage.obdAddedCodesList: 'الأكواد المضافة',
    InspectionPage.obdPairNewDevice: 'إقران جهاز',
    InspectionPage.stepLabel: 'الخطوة @step',
    InspectionPage.submitValidationTitle: 'لا يمكن الإرسال',
    InspectionPage.submitValidationMsg: 'يرجى إكمال جميع الخطوات قبل الإرسال:',
    InspectionPage.submitSuccessTitle: 'تم الإرسال',
    InspectionPage.submitSuccessMsg: 'تم إرسال الفحص بنجاح',
    InspectionPage.stepIncomplete: '@step غير مكتمل',
    InspectionPage.stepVehicleInfo: 'معلومات المركبة',
    InspectionPage.stepPoints: 'نقاط الفحص',
    InspectionPage.stepPhotos: 'الصور',
    InspectionPage.stepBody: 'ملاحظات الهيكل',
    InspectionPage.stepObd: 'OBD',
    InspectionPage.vehicleInfoRequired: 'معلومات المركبة مطلوبة',
    InspectionPage.vehicleInfoRequiredMsg:
        'يرجى ملء جميع حقول معلومات المركبة قبل المتابعة',
    InspectionPage.allPointsRequired: 'جميع النقاط مطلوبة',
    InspectionPage.allPointsRequiredMsg:
        'يرجى ملء جميع نقاط الفحص قبل المتابعة',
    InspectionPage.pointsRequired: 'النقاط مطلوبة',
    InspectionPage.pointsRequiredMsg: 'يجب ملء نقطة فحص واحدة على الأقل',
    InspectionPage.photosRequired: 'الصور مطلوبة',
    InspectionPage.photosRequiredMsg:
        'يجب رفع صورة واحدة على الأقل قبل المتابعة',
    InspectionPage.allPhotosRequired: 'جميع الصور مطلوبة',
    InspectionPage.allPhotosRequiredMsg:
        'يرجى رفع جميع الصور المطلوبة قبل المتابعة',

    /// End Inspection Details Page
    ///
    /// Details Page
    DetailsPage.pageTitle: 'فحص رقم. @inspection',
    DetailsPage.reviewNoteTitle: 'ملاحظات المراجع : ',
    DetailsPage.vehicleInfoTile: 'معلومات المركبة',
    DetailsPage.requestInfoTitle: 'معلومات الطلب',
    DetailsPage.inspectionPointResults: 'نتائج نقاط الفحص',
    DetailsPage.defaultValidationIfNull: 'The value must be entered',
    DetailsPage.defaultValidation: 'The value must be of 3 characters or more',

    DetailsPage.vin: 'الرقم التسلسلي للمركبة',
    DetailsPage.vinHint: 'أدخل رقم التسلسلي للمركبة',
    DetailsPage.vinValidationIfNull:
        'مافي انسان بدون اثبات و أكيد مافي موتر بدون اثباته (;',
    DetailsPage.vinValidation: '17 حرف و رقم يا ليت تكتبهم بالكامل',
    DetailsPage.vinSearchBtn: 'بحث',
    DetailsPage.vinSearching: 'جاري البحث...',
    DetailsPage.vinFound: 'تم العثور على بيانات المركبة',
    DetailsPage.vinFoundMsg: 'تم تعبئة الحقول تلقائياً، يمكنك التعديل عليها.',
    DetailsPage.vinNotFound: 'لم يتم العثور على المركبة',
    DetailsPage.vinNotFoundMsg:
        'لا توجد بيانات لهذا الرقم، يمكنك الإدخال يدوياً.',
    DetailsPage.vinSearchError: 'خطأ في البحث',
    DetailsPage.vinSearchErrorMsg: 'تعذر البحث، حاول مرة أخرى.',
    DetailsPage.vinHelperTyping: 'أدخل 17 حرف للبحث عن بيانات المركبة تلقائياً',
    DetailsPage.vinHelperReady:
        'اضغط على أيقونة البحث لتعبئة البيانات تلقائياً',
    DetailsPage.sectionIdentification: 'التعريف',
    DetailsPage.sectionSpecifications: 'المواصفات',
    DetailsPage.sectionInterior: 'الألوان والمقاعد',

    DetailsPage.plateNumber: 'رقم اللوحة',
    DetailsPage.plateNumberHint: 'أدخل رقم اللوحة',
    DetailsPage.plateNumberValidationIfNull: 'مطلوب ...',
    DetailsPage.plateNumberValidation: 'أكمل اللوحة: مطلوب 3 أحرف و 4 أرقام',
    'plateLettersLabel': 'الحروف',
    'plateNumbersLabel': 'الأرقام',
    DetailsPage.bodyType: 'هيكل المركبة',
    DetailsPage.bodyTypeValidation: 'حدد هيكل المركبة ما راح نطقها عين',

    DetailsPage.drivetrain: 'نظام الدفع',
    DetailsPage.drivetrainValidation: 'أول سيارة تطير !',

    DetailsPage.fuelType: 'نوع الوقود',
    DetailsPage.fuelTypeValidation: 'ع الطاقة الشمسية ؟!',

    DetailsPage.gasolineType: 'نوع البنزبن',
    DetailsPage.gasolineTypeValidation: 'يمكن نحتاجها',

    DetailsPage.milage: 'قراءة العداد',
    DetailsPage.milageHint: 'كم ممشاها ؟!',
    DetailsPage.milageValidationIfNull:
        'أجل ليه تفحصها و عادها خرجت من الوكالة',
    DetailsPage.milageValidation: 'يجب ان تكون بالارقام و بقياس ال كم',

    DetailsPage.yearModel: 'سنة الصنع',
    DetailsPage.yearModelValidation: 'متى ولدت ؟ عشان نسوي لها عيد مبلاد !',

    DetailsPage.exteriorColor: 'لون المركبة الخارجي',
    DetailsPage.exteriorColorHint: 'Enter Exterior Color',
    DetailsPage.exteriorColorValidation: 'Automatic',

    DetailsPage.interiorColor: 'لون المركبة الداخلي',
    DetailsPage.interiorColorHint: 'اختر اللون الداخلي',
    DetailsPage.interiorColorValidation: 'Automatic',
    'colorSelectHint': 'اختر لوناً',

    DetailsPage.gearboxType: 'نوع التروس',
    DetailsPage.gearboxTypeValidation: 'Automatic',

    DetailsPage.cylindersNo: 'عدد السليندر',
    DetailsPage.cylindersNoValidation: 'لازم تدخل العدد عشان الفحص',

    DetailsPage.engineSize: 'مقاس المحرك CC',
    DetailsPage.engineSizeHint: 'أدخل مقاس المحرك (CC) مثل: 2.4, 2400',
    DetailsPage.engineSizeValidationIfNull: 'هل هناك مركبه لا تمتلك محرك ؟!',
    DetailsPage.engineSizeValidation: 'مسموح بالارقام الصحيحه و العشريه فقط.',

    DetailsPage.seatType: 'نوع المقاعد',
    DetailsPage.seatTypeValidation: 'نوع المقاعد مطلوب',

    DetailsPage.seatNo: 'عدد المقاعد',
    DetailsPage.seatNoValidation: 'عدد المقاعد مطلوب',

    /// End Details Page
    ///
    /// Inspection Point Page
    InspectionPage.generatDialogTitle: 'تحذير !',
    InspectionPage.generatDialogContent:
        'هل أنت متاكد؟ هذا الإجراء سيحذف كل النقاط و يعيد بناءها من جديد, كل المعلومات المحفوظة سيتم حذفها.',
    InspectionPage.generatDialogConfirmBtn: 'إعادة تعيين',
    InspectionPage.generatDialogCancel: 'إلغاء',

    /// End Inspection Point Page
    FTexts.saveBtn: 'حفظ',
    FTexts.editBtn: 'تعديل',
    FTexts.reviewBtn: 'مراجعة الفحص',

    'veriCode': 'أدخل رقم التحقق',
    'verify': 'التحقق',
    'Enter OTP': 'ادخل رمز التحقق',
    'OTP': 'رمز التحقق',
    'Validation': 'التحقق',
    'Please ensure your all entries are correct':
        'الرجاء التأكد من جميع المدخلات "جميعها مطلوبه',
    'Enter VIN': 'ادخل الرقم التسلسلي للمركبة',
    'Enter Plate Number': 'ادخل رقم اللوحة',
    'Request ID': 'رقم الطلب',
    'Body Type': 'نوع الهيكل',
    'Vehicle Drivetrain': 'نظام نقل الحركة',
    'Fuel Type': 'نوع الوقود',
    'Milage': 'كم ميل',
    'Enter Milage': 'ادخل كم ماشيه ميل',
    'Brand': 'شركة التصنيع',
    'Model': 'الموديل',
    'Year Model': 'سنة الصنع',
    'Color': 'لون المركبة',
    'Enter Color': 'ادخل اللون الخارجي للمركبة',
    'Seat Color': 'اللون الداخلي',
    'Enter Seat Color': 'ادخل اللون الداخلي للمركبة',
    'Gearbox Type': 'نوع التروس',
    'Cylinders No': 'عدد السليندر',
    'Engine Size CC': 'سعة المحرك CC',
    'Enter Engine Size (CC)': 'ادخل سعة المحرك مثل 2.5',
    'Seat Type': 'نوع المقاعد',
    'Seats No': 'عدد المقاعد',
    'Inspection Points': 'نقاط الفحص',
    'Photos': 'الصور',
    'Vehicle Body': 'هيكل المركبة',
    'OBD': 'OBD',
    'Choose One': 'حدد أختيار',
    'Add an additional photo': 'دخال صوره إضافية',
    'Interior Photos': 'صور داخلية',
    'Exterior Photos': 'صور خارجية',
    'Interior Notes': 'ملاحظات داخلية',
    'Exterior Notes': 'ملاحظات خارجية',
    'OBD Codes': 'رموز OBD',
    'Description': 'وصف الرمز',
    'Code': 'الرمز',
    'Type description here': 'أكتب وصف الرمز هنا',
    'Successful Saved': 'تم الحفظ بنجاح',
    'Your inspection results have saved successfully.':
        'جميع نتائج الفحص الخاصة بك تم حفظها بنجاح.',
    'The Car Plate must be entered': 'يجب ادخال رقم لوحة السيارة',
    'The Car Plate length must be less than 9':
        'رقم لوحة السيارة يجب أن يكون أقل من 9 حروف و أرقام',
    'The last 6 charts in Car Plate must be numbers':
        'أخر 6 رموز من لوحة السيارة يجب أن يكون ارقام',
    'The First 3 charts in Car Plate must be letters':
        'أول 3 رموز من لوحة السيارة يجب أن يكون حروف',
    'The Milage must be entered': 'رقم ميل يجب أن يتم إدخاله',
    'The Milage must be numbers': 'قيمة الميل يجب أن تكون أرقام',
    'The Engine Size must be entered': 'مقاس المحرك CC يجب أن يتم إدخاله',
    'The Engine Size must be normal numbers or decimal':
        'مقاس المحرك CC يجب ان يكون أرقام طبيعية او عشرية',
    'The VIN must be entered': 'الرقم التسلسلي للمركبة يجب أن يتم إدخاله',
    'The VIN length must be 17':
        'طول الرقم التسلسلي للمركبة يجب أن يكون 17 رمز',
    'The value must be entered': 'الحقل مطلوب',
    'The value must be of 3 characters or more':
        'الحقل يجب أن يكون 3 احرف او أكثر',
    'Delete': 'حذف',
    'Type your note here': 'أكتب ملاحظتك هنا',
    'Add Note': 'إضافة ملاحظة',
    'Provide valid Email': 'البريد الإلكتروني غير صحيح',
    'Not updated': 'لم يرفع',
    'Saved locally': 'محفوظ',
    'Uploading ...': 'جاري الرفع...',
    'Downloading ...': 'جاري التنزيل...',
    'General Note': 'ملاحظات عامة',
    'Enter general note ....': 'ادخل ملاحظة عامة',
    'disconnected_message':
        '''لست متصل بالإنتارنت كما هو ظاهر ,رجاء‘ تحقق من اتصالك ثم اعد المحاوله.''',
    'network_connection': 'حالة الاتصال بالشبكة',
    'Reload': 'إعادة المحاوله',
    'Continue with offline': 'المتابع بدون اتصال',
    'There is no more requests': 'لم يعد هناك المزيد من الطلبات',
    "It's seems you are logged out, Offline mode is allowed while you are logged in":
        "أنت لست مسجل دخول, وضع عدم الأتصال يحتاج الى تسجبل دخولك",
    'Update': 'تحديث',
    'Skip': 'تخطي',
    'update_message':
        'لقد توفر تحديث جديد للتطبيق إصدار : @newVer ,@isShould تحديثه الأن.',
    'there_update': 'يوجد خبر سعيد',
    'have_to': 'ينبغي',
    'can': 'تستطيع',
    'is_not_enable_to_using_offline_mood':
        "ربما لم تسجل دخولك او أنك لم تحمل البيانات الاساسية لإستخدام وضع عدم الإتصال, رجاء‘ تأكد من إعدادات التطبيق",
    'App Settings': 'إعدادات التطبق',
    'General Settings': 'إعدادات عامة',
    'Offline Mode Settings': 'إعدادات وضع عدم الإتصال',
    'Permission Required': 'صلاحية الوصول مطلوبة',
    'You must to give a permission to can use camera or select image from gallery':
        'ساعدنا للحصول على تصريحك للوصول للكاميرا او البوم الصور الخاص بك من الإعدادات',
    'Go to settings': 'الذهاب للإعدادات',
    'Welcome back': 'لقد كنا بإنتظارك',
    'Remember Me': 'تذكرني',
    'Add OBD code': 'إضافة رمز الOBD',
    'Type OBD code here': 'أدخل رمز الOBD هنا',
    'Searching Code Description...': 'جاري البحث عن الرمز...',
    'Type Code Description': 'أدخل وصف الرمز هنا',
    'Add': 'إضافة',
    'Request Information': 'معلومات الطلب',
    'Inspection Point Results': 'نتائج نقاط الفحص',
    'Point Categories': 'تصنيف النقاط',

    'The file is not PDF, You should to upload PDF file.':
        'الملف الذي حددته ليس من نوع PDF, فضلاً اختار ملف PDF',
    'Edit General Note': 'تحرير ملاحظات عامة',
    'Type General Note for the inspection':
        'أدخل ملاحظاتك العامه على طلب الفحص',
    'Are You Sure?': 'هل تريد الحفظ',
    'Do you want to save all modified values ? Or want to get back without saving any values ?':
        'يوجد معلومات تم التعديل عليها, هل تريد حفظها ؟ يمكنك الخروج دون حفظ المعلومات او الإلغاء.',
    'Save': 'حفظ',
    'Exit': 'لا تحفظ',
    'There is no OBD Code': 'لا يوجد رموز OBD مسجله بعد',
    'EditNumber': 'تعديل رقم الجوال',

    /// Body Notes / Marker Dialog
    FTexts.markerTitle: 'إضافة ملاحظة',
    FTexts.markerInputTitle: 'الملاحظة',
    FTexts.markerInputHint: 'صف المشكلة...',
    FTexts.markerSelectTitle: 'حدد نوع الملاحظة',
    FTexts.markerNoteRequired: 'الملاحظة مطلوبة',
    FTexts.markerNoteRequiredMsg: 'يجب وصف المشكلة',
    FTexts.markerTypeRequired: 'النوع مطلوب',
    FTexts.markerTypeRequiredMsg: 'يجب تحديد نوع الملاحظة',
    FTexts.markerAddPhoto: 'التقاط صورة',
    FTexts.markerChangePhoto: 'تغيير الصورة',
    FTexts.bodyInspectionDetails: 'تفاصيل الفحص',
    FTexts.bodyTapHint: 'اضغط لإضافة علامة',
    FTexts.bodyDragHint: 'اسحب العلامة لتغيير موضعها',

    /// Body part labels
    FTexts.bodyPartTop: 'أعلى',
    FTexts.bodyPartLeft: 'يسار',
    FTexts.bodyPartRight: 'يمين',
    FTexts.bodyPartFront: 'أمام',
    FTexts.bodyPartBack: 'خلف',
    FTexts.bodyPartInterior: 'داخلي',

    /// Marker success / error
    FTexts.markerSavedSuccess: 'تم الحفظ',
    FTexts.markerSavedSuccessMsg: 'تم حفظ الملاحظة بنجاح',
    FTexts.markerMovedSuccess: 'تم تحديث الموضع',
    FTexts.markerMovedSuccessMsg: 'تم تحديث موضع الملاحظة بنجاح',
    FTexts.markerDeletedSuccess: 'تم الحذف',
    FTexts.markerDeletedSuccessMsg: 'تم حذف الملاحظة بنجاح',
    FTexts.markerErrorTitle: 'خطأ',
    FTexts.markerErrorMsg: 'حدث خطأ، يرجى المحاولة مرة أخرى',
    FTexts.systemInspector: 'مفتش النظام',
    FTexts.profileTitle: 'الملف الشخصي',
    FTexts.logoutBtn: 'تسجيل الخروج',
    FTexts.logoutConfirmTitle: 'تسجيل الخروج',
    FTexts.logoutConfirmMessage: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    FTexts.loggingOutTitle: 'جاري تسجيل الخروج',
    FTexts.loggingOutSubtitle: 'يرجى الانتظار...',
    FTexts.profileName: 'الاسم',
    FTexts.profileEmail: 'البريد الإلكتروني',
    FTexts.profilePhone: 'رقم الجوال',
    FTexts.profileCity: 'اختر المدينة',
    FTexts.profileUpdate: 'تحديث',
    FTexts.profileNameHint: 'أدخل الاسم',
    FTexts.profileEmailHint: 'أدخل البريد الإلكتروني',
    FTexts.profilePhoneHint: 'أدخل رقم الجوال',
    FTexts.deleteAccountBtn: 'حذف الحساب',
    FTexts.deleteAccountConfirmTitle: 'حذف الحساب',
    FTexts.deleteAccountConfirmMessage:
        'هل أنت متأكد من حذف حسابك بشكل نهائي؟ لا يمكن التراجع عن هذا الإجراء.',
    FTexts.deleteAccountError: 'فشل حذف الحساب. يرجى المحاولة مرة أخرى.',
    FTexts.deleteAccountSuccess: 'تم حذف حسابك بنجاح.',

    /// Inspection Stage Labels
    FTexts.stageAll: 'الكل',
    FTexts.stagePending: 'قيد الانتظار',
    FTexts.stageAccepted: 'مقبول',
    FTexts.stageInfo: 'معلومات المركبة',
    FTexts.stagePoints: 'نقاط الفحص',
    FTexts.stagePhotos: 'الصور',
    FTexts.stageBody: 'ملاحظات الهيكل',
    FTexts.stageObd: 'OBD',
    FTexts.stageFinished: 'منتهي',
    FTexts.stageRejected: 'مرفوض',
    FTexts.stageReviewed: 'معتمد',
    'Search...': 'بحث...',

    /// Home Screen Segments
    'Companies': 'شركات',
    'Individuals': 'أفراد',
    'requests': 'طلبات',
    'No company requests': 'لا توجد طلبات شركات',
    'No individual requests': 'لا توجد طلبات أفراد',
    'No results found': 'لا توجد نتائج',

    /// Notifications Screen
    'Notifications': 'الإشعارات',
    'No notifications yet': 'لا توجد إشعارات بعد',
    'You will see your notifications here': 'ستظهر إشعاراتك هنا',
    'Just now': 'الآن',

    /// Team & Profile
    'Switch Team': 'تبديل الفريق',
    'Teams': 'الفرق',
    'Current': 'الحالي',
    'Team Switched': 'تم تبديل الفريق',
    'Error': 'خطأ',
    'Failed to switch team': 'فشل تبديل الفريق',
    'Change Photo': 'تغيير الصورة',
    'Camera': 'الكاميرا',
    'Gallery': 'المعرض',
    'Dark Mode': 'الوضع الداكن',
    'Light Mode': 'الوضع الفاتح',
    'No Permission': 'غير مسموح',
    'Unauthenticated': 'غير مصرح',
    'No Connection': 'لا يوجد اتصال',
    'Server Error': 'خطأ في الخادم',
    'Invalid data': 'بيانات غير صالحة',
    'Not Found': 'غير موجود',
    'Unknown Error': 'خطأ غير معروف',

    /// Select Team Screen
    'Select Team to Continue': 'اختر الفريق للمتابعة',
    'Please select a team to continue using the app':
        'يرجى اختيار فريق للمتابعة في استخدام التطبيق',
    'No teams available': 'لا توجد فرق متاحة',
    'Pull down to refresh': 'اسحب للأسفل للتحديث',

    /// Onboarding
    'getStarted': 'ابدأ الآن',
    'onBoardingTitle1': 'إدارة الفحوصات',
    'onBoardingSubTitle1':
        'عرض وإدارة جميع طلبات فحص المركبات في مكان واحد — بسهولة وكفاءة.',
    'onBoardingTitle2': 'افحص بدقة',
    'onBoardingSubTitle2':
        'اتبع مراحل الفحص خطوة بخطوة: الصور، فحص الهيكل، تشخيص OBD، والمزيد.',
    'onBoardingTitle3': 'ابقَ على اطلاع',
    'onBoardingSubTitle3':
        'استقبل الإشعارات الفورية وتابع كل تحديث على حالة الفحص.',

    /// OTP
    'enterOTP': 'أدخل رمز التحقق',
    'otpSentTo': 'تم إرسال رمز التحقق إلى',
    'otpSending': 'جاري إرسال رمز التحقق إلى',
    'otpSentMessage': 'أرسلنا رمز التحقق إلى رقمك. يرجى إدخاله أدناه.',
    'resendOTP': 'إعادة إرسال الرمز',
    'resendIn': 'إعادة الإرسال خلال ',
    'secondsShort': 'ث',

    /// Camera
    FTexts.cameraRetake: 'إعادة التقاط',
    FTexts.cameraUsePhoto: 'استخدام الصورة',
    FTexts.cameraRetry: 'إعادة المحاولة',
    FTexts.cameraOk: 'موافق',
    FTexts.imageSourceCamera: 'الكاميرا',
    FTexts.imageSourceGallery: 'البوم الصور',
    FTexts.cameraCaptureFailed: 'فشل التقاط الصورة، يرجى المحاولة مرة أخرى',
    FTexts.cameraPermissionDeniedTitle: 'تم رفض الوصول إلى الكاميرا',
    FTexts.cameraPermissionDenied:
        'يرجى السماح بالوصول إلى الكاميرا من الإعدادات للمتابعة.',

    /// Force Update
    FTexts.forceUpdateTitle: 'تحديث مطلوب',
    FTexts.forceUpdateMessage:
        'يتوفر إصدار جديد من التطبيق. يرجى التحديث للمتابعة في استخدام التطبيق.',
    FTexts.forceUpdateButton: 'تحديث الآن',

    /// Access Request
    AccessRequestPage.welcomeTitle: 'مرحبًا بك في فاحص',
    AccessRequestPage.welcomeSubtitle: 'اختر كيف تود المتابعة',
    AccessRequestPage.alreadyMember: 'لديك حساب بالفعل',
    AccessRequestPage.requestMembership: 'التقديم للعمل كفني',
    AccessRequestPage.requestFormTitle: 'طلب الانضمام كفني',
    AccessRequestPage.fullName: 'الاسم الكامل',
    AccessRequestPage.fullNameHint: 'أدخل اسمك الكامل',
    AccessRequestPage.email: 'البريد الإلكتروني',
    AccessRequestPage.emailHint: 'أدخل بريدك الإلكتروني',
    AccessRequestPage.phone: 'رقم الهاتف',
    AccessRequestPage.phoneHint: 'أدخل رقم هاتفك',
    AccessRequestPage.city: 'المدينة',
    AccessRequestPage.cityHint: 'أدخل مدينتك',
    AccessRequestPage.note: 'معلومات إضافية (اختياري)',
    AccessRequestPage.noteHint: 'اذكر أي خبرة ذات صلة',
    AccessRequestPage.submitRequest: 'إرسال الطلب',
    AccessRequestPage.requestSuccessTitle: 'تم إرسال الطلب بنجاح',
    AccessRequestPage.requestSuccessSubtitle:
        'تم استلام طلبك. سيقوم فريقنا بمراجعته والتواصل معك قريبًا.',
    AccessRequestPage.doneBtn: 'تم',
    AccessRequestPage.submissionFailed: 'فشل الإرسال',
    AccessRequestPage.submissionFailedMsg:
        'حدث خطأ ما، يرجى المحاولة مرة أخرى.',

    /// Paint Gauge
    PaintGaugePage.stepTitle: 'قياس البوية',
    PaintGaugePage.scanTitle: 'توصيل جهاز القياس',
    PaintGaugePage.scanSubtitle:
        'شغّل البلوتوث وضع جهاز Guoou بالقرب منك للبحث',
    PaintGaugePage.scanButton: 'بحث عن الأجهزة',
    PaintGaugePage.stopScanButton: 'إيقاف البحث',
    PaintGaugePage.noDevicesFound: 'لم يتم العثور على أجهزة',
    PaintGaugePage.noDevicesSubtitle: 'اضغط على "بحث عن الأجهزة" للبدء',
    PaintGaugePage.scanning: 'جاري البحث...',
    PaintGaugePage.scanningSubtitle: 'يتم البحث عن أجهزة البلوتوث القريبة',
    PaintGaugePage.namedDevices: 'الأجهزة المعروفة',
    PaintGaugePage.unnamedDevices: 'أجهزة غير معروفة',
    PaintGaugePage.btNotSupported: 'البلوتوث غير مدعوم في هذا الجهاز',
    PaintGaugePage.btNotEnabled: 'يرجى تفعيل البلوتوث',
    PaintGaugePage.btPermissionRequired: 'يرجى منح صلاحية البلوتوث',
    PaintGaugePage.skipStep: 'تخطي هذه الخطوة',
    PaintGaugePage.connecting: 'جاري الاتصال...',
    PaintGaugePage.connected: 'متصل',
    PaintGaugePage.disconnected: 'غير متصل',
    PaintGaugePage.lostConnection: 'انقطع الاتصال',
    PaintGaugePage.connectionError: 'خطأ في الاتصال',
    PaintGaugePage.goBack: 'إلغاء الاتصال',
    PaintGaugePage.connectButton: 'الاتصال بالجهاز',
    PaintGaugePage.connectHint: 'اضغط للاتصال بالجهاز',
    PaintGaugePage.sessionReadingsOnly:
        'قراءات الجلسة فقط — لم يتم استيراد بيانات سابقة',
    PaintGaugePage.measuredPanels: 'تم قياسه',
    PaintGaugePage.noMeasurementYet: 'لا توجد قراءة بعد',
    PaintGaugePage.tapToMoveDevice: 'اضغط لنقل الجهاز هنا',
    PaintGaugePage.readings: 'قراءات',
    PaintGaugePage.average: 'المتوسط',
    PaintGaugePage.substrate: 'نوع المادة',
    PaintGaugePage.here: 'هنا',
    PaintGaugePage.clearPanel: 'مسح اللوحة',
    PaintGaugePage.clearPanelConfirm:
        'سيتم مسح جميع قراءات هذه اللوحة في الجلسة الحالية.',
    PaintGaugePage.clearAll: 'مسح جميع اللوحات',
    PaintGaugePage.clearAllConfirm: 'سيتم حذف جميع القراءات من كل اللوحات.',
    PaintGaugePage.clearSuccess: 'تم الحذف بنجاح',
    PaintGaugePage.clearFailed: 'فشل مسح اللوحة',
    PaintGaugePage.reviewTitle: 'قياس البوية',
    PaintGaugePage.reviewPanelsMeasured: 'لوحة تم قياسها',
    PaintGaugePage.reviewNoData: 'لا توجد قراءات مسجلة',
    PaintGaugePage.panelHood: 'الكبوت',
    PaintGaugePage.panelRoof: 'السقف',
    PaintGaugePage.panelTrunk: 'الشنطة',
    PaintGaugePage.panelLeftFrontFender: 'الرفرف الأمامي الأيسر',
    PaintGaugePage.panelLeftAPillar: 'العمود A الأيسر',
    PaintGaugePage.panelLeftFrontDoor: 'الباب الأمامي الأيسر',
    PaintGaugePage.panelLeftBPillar: 'العمود B الأيسر',
    PaintGaugePage.panelLeftRearDoor: 'الباب الخلفي الأيسر',
    PaintGaugePage.panelLeftCPillar: 'العمود C الأيسر',
    PaintGaugePage.panelLeftRearFender: 'الرفرف الخلفي الأيسر',
    PaintGaugePage.panelLeftDPillar: 'العمود D الأيسر',
    PaintGaugePage.panelRightDPillar: 'العمود D الأيمن',
    PaintGaugePage.panelRightRearFender: 'الرفرف الخلفي الأيمن',
    PaintGaugePage.panelRightCPillar: 'العمود C الأيمن',
    PaintGaugePage.panelRightRearDoor: 'الباب الخلفي الأيمن',
    PaintGaugePage.panelRightBPillar: 'العمود B الأيمن',
    PaintGaugePage.panelRightFrontDoor: 'الباب الأمامي الأيمن',
    PaintGaugePage.panelRightAPillar: 'العمود A الأيمن',
    PaintGaugePage.panelRightFrontFender: 'الرفرف الأمامي الأيمن',

    // رسائل الوضع غير المتصل / المزامنة
    'saved_locally_will_sync': 'تم الحفظ — ستتم المزامنة عند الاتصال',
    'offline_no_cached_orders':
        'أنت غير متصل — ستظهر الفحوصات عند عودة الاتصال',
    'offline_bar_message': 'لا يوجد اتصال — تحقق من الإنترنت',
    'back_online_title': 'عاد الاتصال',
    'back_online_message': 'جارٍ مزامنة التغييرات المعلّقة…',
    'syncing_offline_changes': 'جارٍ مزامنة التغييرات غير المتصلة',
    'offline_no_cache_message':
        'لم يتم تنزيل هذا الفحص بعد. أعد الاتصال واسحب للأسفل للتحديث.',
    'saved_locally_title': 'تم الحفظ محليًا',
    'saved_locally_message': 'ستتم المزامنة تلقائيًا عند عودة الاتصال.',
    'queued_delete_title': 'في قائمة الحذف',
    'queued_delete_message': 'سيتم حذفه عند عودة الاتصال.',
    'report_not_cached_title': 'التقرير غير متاح دون اتصال',
    'report_not_cached_message': 'اتصل بالإنترنت لتحميل التقرير لأول مرة.',
  };
}
