import '../constants/text_strings.dart';

class Arabic {
  Arabic._();

  static Map<String, String> ar = {
    /// Global Texts
    FTexts.appName: 'فاحص',
    FTexts.cancelBtn: 'إلغاء',
    FTexts.skip: 'تخطى',
    FTexts.refresh: 'جرب مره ثانيه',
    FTexts.submitBtn: 'إرسال',
    FTexts.nextBtn: 'التالي',
    FTexts.backBtn: 'السابق',
    FTexts.requestId: 'رقم الطلب',
    FTexts.deleteBtn: 'حذف',
    FTexts.signOut: 'تسجيل الخروج',
    FTexts.updateAssets: 'تحديث الموارد',
    FTexts.offlineMode: 'وضع عدم الاتصال',
    'All': 'الكل',
    'Pending': 'معلقة',
    'Accepted': 'مقبولة',
    'In Progress': 'جاري فحصها',
    'Finished': 'منتهية',
    'Rejected': 'مرفوضة',
    'Reviewed': 'تمت مراجعتها',
    'Settings & Support': 'الإعدادات و الدعم',
    'Help & Support': 'الإعدادات و الدعم',

    /// End Global Texts
    ///
    /// Enums Texts
    FTexts.automatic: 'اوتوماتيك',
    FTexts.manual: 'عادي',
    FTexts.fabric: 'قماش',
    FTexts.leather: 'جلد',
    FTexts.inProgress: 'جاري الفحص',
    FTexts.pended: 'معلق',
    FTexts.approved: 'موثق',
    FTexts.finished: 'منتهي',
    FTexts.good: 'جيد',
    FTexts.notes: 'ملاحظة',
    FTexts.na: 'لا يوجد',
    FTexts.unSelected: 'غير محدد',
    ForgetPage.forgetSubTitle: 'ادخل رقم جوالك و راح نرسل لك رمز التحقق',
    FTexts.more: 'المزيد',

    /// End Enums Texts
    ///
    /// Login Page
    LoginPage.loginTitle: 'تطبيق مراكز الفحص',
    LoginPage.loginSubTitle: 'مرحباً بعودتك ,..',
    LoginPage.phoneNumber: 'رقم الجوال',
    LoginPage.phoneNumberValidation: 'يجب ان يكون رقم جوال صحيح',
    LoginPage.username: 'البريد الإلكتروني او الجوال',
    LoginPage.emailValidation: 'يجب ان تكون كلمة المرور اكبر من 8 رموز',
    LoginPage.password: 'كلمة المرور',
    LoginPage.passwordValidation: 'لازم تدخل الباسورد عشان السريه و كذا',
    LoginPage.rememberMe: 'تذكرني',
    LoginPage.signIn: 'تسجيل الدخول',
    LoginPage.verifyOTP: 'تحقق',
    LoginPage.resetPassword: 'إعادة تعيين كلمة المرور',
    LoginPage.forgetBTN: 'نسيت كلمة المرور؟',
    LoginPage.loginWithEmail: 'الدخول بأستخدام البريد الإلكتروني',
    LoginPage.otpTitle: 'أدخل رقم التحقق',
    LoginPage.resendBtnWithTime: 'إعادة الإرسال (بعد @s ث)',
    LoginPage.resendBtn: 'إعادة الإرسال',
    LoginPage.editPhoneNumber: 'تعدبل رقم الهاتف',
    LoginPage.processingTitle:
        '...يتم تسجيل الدخول و تجهيز البيانات (لن يستغرق سوا ثواني)',

    /// End Login Page
    ///
    /// Home Page
    HomePage.searchHint: 'البحث باستخدام رقم اللوحة....',
    HomePage.request: 'الطلبات',
    HomePage.searchPlaceholder: 'أبحث...',
    HomePage.history: 'سجل الطلبات',
    HomePage.onEmpty: 'onEmpty',
    HomePage.onError: 'There is an error occurred',
    HomePage.noMore: 'لا يوجد لديك طلبات حالياً',

    /// End Home Page
    ///
    /// Inspection Details Page
    InspectionPage.generalInfo: 'المعلومات العامة',
    InspectionPage.vehicleInfo: 'معلومات المركبة',
    InspectionPage.connectPersonInfo: 'معلومات التواصل',
    InspectionPage.inspectionPointReview: 'ملخص نقاط الفحص',
    InspectionPage.inspectionType: 'نوع الفحص',
    InspectionPage.center: 'مركز الفحص',
    InspectionPage.centerBranch: 'فرع مركز الفحص',
    InspectionPage.city: 'مدينة المركز',
    InspectionPage.bookingDate: 'تاريخ الحجز',
    InspectionPage.assignedTo: 'إسناد الفحص لـ',
    InspectionPage.inspector: 'أسم الفاحص',
    InspectionPage.inspectedAt: 'تاريخ الفحص',
    InspectionPage.reviewedAt: 'تاريخ المراجعة',
    InspectionPage.createdAt: 'تاريخ الإنشاء',
    InspectionPage.inspectorNote: 'ملاحظة الفاحص',
    InspectionPage.reviewerNote: 'ملاحظة المراجع',
    InspectionPage.notYet: 'لم يحدد بعد',
    InspectionPage.anyInspector: 'كل الفاحصين',
    InspectionPage.vin: 'رقم الهيكل',
    InspectionPage.serialNo: 'رقم بيانات المركبة',
    InspectionPage.make: 'الشركة المصنعة',
    InspectionPage.model: 'الموديل',
    InspectionPage.storageSize: 'حجم الصهريج',
    InspectionPage.vehicleShape: 'شكل صهريج',
    InspectionPage.yearModel: 'سنة الموديل',
    InspectionPage.plate: 'رقم اللوحة',
    InspectionPage.contactName: 'الاسم',
    InspectionPage.contactEmail: 'البريد الإلكتروني',
    InspectionPage.contactPhone: 'الجوال',
    InspectionPage.contactCity: 'المدينة',
    InspectionPage.inspectionPhotos: 'صور الفحص',
    InspectionPage.inspectionBodyNotes: 'ملاحظات هيكل المركبة',
    InspectionPage.inspectionOBDCodes: 'رموز OBD للفحص',
    InspectionPage.loadingInspectionDetails: 'جاري تحميل تفاصيل الفحص...',
    InspectionPage.noteLabel: 'ملاحظة @index',
    InspectionPage.positionLabel: 'الموقع: (@dx, @dy)',
    InspectionPage.notesCount: '@count ملاحظات',
    InspectionPage.pointsReview: 'مراجعة النقاط',
    InspectionPage.inspectionDetailsTitle: 'تفاصيل الفحص',
    InspectionPage.doneBtn: 'تم',
    InspectionPage.imageRequired: 'الصورة مطلوبة',
    InspectionPage.imageRequiredMsg: 'يجب توثيق الملاحظة بصورة توضح الحالة',
    InspectionPage.noteRequired: 'الملاحظة مطلوبة',
    InspectionPage.noteRequiredMsg: 'يجب وصف الحالة',
    InspectionPage.resetPointsTitle: 'إعادة تعيين النقاط',
    InspectionPage.resetPointsContent:
        'هل أنت متأكد من إعادة تعيين جميع النقاط؟ سيتم حذف جميع التغييرات على النقاط الحالية.',
    InspectionPage.resetPointsConfirm: 'إعادة تعيين',
    InspectionPage.selectStatus: 'اختر الحالة',
    InspectionPage.addNoteTitle: 'إضافة ملاحظة',
    InspectionPage.noteHint: 'اكتب ملاحظتك هنا...',
    InspectionPage.noteFieldLabel: 'الملاحظة',
    InspectionPage.noteValidation: 'الملاحظة مطلوبة',
    InspectionPage.photosTitle: 'الصور',
    InspectionPage.uploadedPhotos: 'تم الرفع',
    InspectionPage.availablePhotos: 'متاحة',
    InspectionPage.photoUploaded: 'تم الرفع',
    InspectionPage.addPhoto: 'إضافة صورة',
    InspectionPage.selectPhotoTitle: 'اختر الصورة لالتقاطها',
    InspectionPage.noPhotosYet: 'لا توجد صور بعد',
    InspectionPage.photosProgress: '@uploaded / @total صور',
    InspectionPage.takePhoto: 'التقاط صورة',
    InspectionPage.deletePhoto: 'حذف الصورة',
    InspectionPage.startInspection: 'ابدأ الفحص',
    InspectionPage.generalNoteTitle: 'إرسال الفحص',
    InspectionPage.rejectionNoteTitle: 'رفض الفحص',
    InspectionPage.noteOptionalHint: 'أضف ملاحظة (اختياري)...',
    InspectionPage.confirmSubmit: 'تأكيد',
    InspectionPage.cancelBtn: 'إلغاء',
    InspectionPage.submitConfirmSubtitle: 'هل أنت متأكد من إرسال هذا الفحص؟',
    InspectionPage.rejectConfirmSubtitle: 'هل أنت متأكد من رفض هذا الفحص؟',
    InspectionPage.addNoteLabel: 'إضافة ملاحظة',
    InspectionPage.optionalTag: 'اختياري',
    InspectionPage.obdFileName: 'اسم الملف',
    InspectionPage.uploadObdReport: 'رفع تقرير OBD',
    InspectionPage.obdCodesTitle: 'أكواد OBD',
    InspectionPage.stepLabel: 'الخطوة @step',
    InspectionPage.submitValidationTitle: 'لا يمكن الإرسال',
    InspectionPage.submitValidationMsg: 'يرجى إكمال جميع الخطوات قبل الإرسال:',
    InspectionPage.submitSuccessTitle: 'تم الإرسال',
    InspectionPage.submitSuccessMsg: 'تم إرسال الفحص بنجاح',
    InspectionPage.stepIncomplete: '@step غير مكتمل',
    InspectionPage.stepVehicleInfo: 'معلومات المركبة',
    InspectionPage.stepPoints: 'نقاط الفحص',
    InspectionPage.stepPhotos: 'الصور',
    InspectionPage.stepBody: 'ملاحظات الهيكل',
    InspectionPage.stepObd: 'OBD',

    /// End Inspection Details Page
    ///
    /// Details Page
    DetailsPage.pageTitle: 'فحص رقم. @inspection',
    DetailsPage.reviewNoteTitle: 'ملاحظات المراجع : ',
    DetailsPage.vehicleInfoTile: 'معلومات المركبة',
    DetailsPage.requestInfoTitle: 'معلومات الطلب',
    DetailsPage.inspectionPointResults: 'نتائج نقاط الفحص',
    DetailsPage.defaultValidationIfNull: 'The value must be entered',
    DetailsPage.defaultValidation: 'The value must be of 3 characters or more',

    DetailsPage.vin: 'الرقم التسلسلي للمركبة',
    DetailsPage.vinHint: 'أدخل رقم التسلسلي للمركبة',
    DetailsPage.vinValidationIfNull:
        'مافي انسان بدون اثبات و أكيد مافي موتر بدون اثباته (;',
    DetailsPage.vinValidation: '17 حرف و رقم يا ليت تكتبهم بالكامل',

    DetailsPage.plateNumber: 'رقم اللوحة',
    DetailsPage.plateNumberHint: 'أدخل رقم اللوحة',
    DetailsPage.plateNumberValidationIfNull: 'مطلوب ...',
    DetailsPage.plateNumberValidation: 'اللوحة تحتوي على حروف و ارقام',

    DetailsPage.bodyType: 'هيكل المركبة',
    DetailsPage.bodyTypeValidation: 'حدد هيكل المركبة ما راح نطقها عين',

    DetailsPage.drivetrain: 'نظام الدفع',
    DetailsPage.drivetrainValidation: 'أول سيارة تطير !',

    DetailsPage.fuelType: 'نوع الوقود',
    DetailsPage.fuelTypeValidation: 'ع الطاقة الشمسية ؟!',

    DetailsPage.gasolineType: 'نوع البنزبن',
    DetailsPage.gasolineTypeValidation: 'يمكن نحتاجها',

    DetailsPage.milage: 'قراءة العداد',
    DetailsPage.milageHint: 'كم ممشاها ؟!',
    DetailsPage.milageValidationIfNull:
        'أجل ليه تفحصها و عادها خرجت من الوكالة',
    DetailsPage.milageValidation: 'يجب ان تكون بالارقام و بقياس ال كم',

    DetailsPage.yearModel: 'سنة الصنع',
    DetailsPage.yearModelValidation: 'متى ولدت ؟ عشان نسوي لها عيد مبلاد !',

    DetailsPage.exteriorColor: 'لون المركبة الخارجي',
    DetailsPage.exteriorColorHint: 'Enter Exterior Color',
    DetailsPage.exteriorColorValidation: 'Automatic',

    DetailsPage.interiorColor: 'لون المقاعد الداخلي',
    DetailsPage.interiorColorHint: 'وش لون المزيونه ؟!',
    DetailsPage.interiorColorValidation: 'Automatic',

    DetailsPage.gearboxType: 'نوع التروس',
    DetailsPage.gearboxTypeValidation: 'Automatic',

    DetailsPage.cylindersNo: 'عدد السليندر',
    DetailsPage.cylindersNoValidation: 'لازم تدخل العدد عشان الفحص',

    DetailsPage.engineSize: 'مقاس المحرك CC',
    DetailsPage.engineSizeHint: 'أدخل مقاس المحرك (CC) مثل: 2.4, 2400',
    DetailsPage.engineSizeValidationIfNull: 'هل هناك مركبه لا تمتلك محرك ؟!',
    DetailsPage.engineSizeValidation: 'مسموح بالارقام الصحيحه و العشريه فقط.',

    DetailsPage.seatType: 'نوع المقاعد',
    DetailsPage.seatTypeValidation: 'نوع المقاعد مطلوب',

    DetailsPage.seatNo: 'عدد المقاعد',
    DetailsPage.seatNoValidation: 'عدد المقاعد مطلوب',

    /// End Details Page
    ///
    /// Inspection Point Page
    InspectionPage.generatDialogTitle: 'تحذير !',
    InspectionPage.generatDialogContent:
        'هل أنت متاكد؟ هذا الإجراء سيحذف كل النقاط و يعيد بناءها من جديد, كل المعلومات المحفوظة سيتم حذفها.',
    InspectionPage.generatDialogConfirmBtn: 'إعادة تعيين',
    InspectionPage.generatDialogCancel: 'إلغاء',

    /// End Inspection Point Page
    FTexts.saveBtn: 'حفظ',
    FTexts.editBtn: 'تعديل',
    FTexts.reviewBtn: 'مراجعة الفحص',

    'veriCode': 'أدخل رقم التحقق',
    'verify': 'التحقق',
    'Enter OTP': 'ادخل رمز التحقق',
    'OTP': 'رمز التحقق',
    'Validation': 'التحقق',
    'Please ensure your all entries are correct':
        'الرجاء التأكد من جميع المدخلات "جميعها مطلوبه',
    'Enter VIN': 'ادخل الرقم التسلسلي للمركبة',
    'Enter Plate Number': 'ادخل رقم اللوحة',
    'Request ID': 'رقم الطلب',
    'Body Type': 'نوع الهيكل',
    'Vehicle Drivetrain': 'نظام نقل الحركة',
    'Fuel Type': 'نوع الوقود',
    'Milage': 'كم ميل',
    'Enter Milage': 'ادخل كم ماشيه ميل',
    'Brand': 'شركة التصنيع',
    'Model': 'الموديل',
    'Year Model': 'سنة الصنع',
    'Color': 'لون المركبة',
    'Enter Color': 'ادخل اللون الخارجي للمركبة',
    'Seat Color': 'اللون الداخلي',
    'Enter Seat Color': 'ادخل اللون الداخلي للمركبة',
    'Gearbox Type': 'نوع التروس',
    'Cylinders No': 'عدد السليندر',
    'Engine Size CC': 'سعة المحرك CC',
    'Enter Engine Size (CC)': 'ادخل سعة المحرك مثل 2.5',
    'Seat Type': 'نوع المقاعد',
    'Seats No': 'عدد المقاعد',
    'Inspection Points': 'نقاط الفحص',
    'Photos': 'الصور',
    'Vehicle Body': 'هيكل المركبة',
    'OBD': 'OBD',
    'Choose One': 'حدد أختيار',
    'Add an additional photo': 'دخال صوره إضافية',
    'Interior Photos': 'صور داخلية',
    'Exterior Photos': 'صور خارجية',
    'Interior Notes': 'ملاحظات داخلية',
    'Exterior Notes': 'ملاحظات خارجية',
    'OBD Codes': 'رموز OBD',
    'Description': 'وصف الرمز',
    'Code': 'الرمز',
    'Type description here': 'أكتب وصف الرمز هنا',
    'Successful Saved': 'تم الحفظ بنجاح',
    'Your inspection results have saved successfully.':
        'جميع نتائج الفحص الخاصة بك تم حفظها بنجاح.',
    'The Car Plate must be entered': 'يجب ادخال رقم لوحة السيارة',
    'The Car Plate length must be less than 9':
        'رقم لوحة السيارة يجب أن يكون أقل من 9 حروف و أرقام',
    'The last 6 charts in Car Plate must be numbers':
        'أخر 6 رموز من لوحة السيارة يجب أن يكون ارقام',
    'The First 3 charts in Car Plate must be letters':
        'أول 3 رموز من لوحة السيارة يجب أن يكون حروف',
    'The Milage must be entered': 'رقم ميل يجب أن يتم إدخاله',
    'The Milage must be numbers': 'قيمة الميل يجب أن تكون أرقام',
    'The Engine Size must be entered': 'مقاس المحرك CC يجب أن يتم إدخاله',
    'The Engine Size must be normal numbers or decimal':
        'مقاس المحرك CC يجب ان يكون أرقام طبيعية او عشرية',
    'The VIN must be entered': 'الرقم التسلسلي للمركبة يجب أن يتم إدخاله',
    'The VIN length must be 17':
        'طول الرقم التسلسلي للمركبة يجب أن يكون 17 رمز',
    'The value must be entered': 'الحقل مطلوب',
    'The value must be of 3 characters or more':
        'الحقل يجب أن يكون 3 احرف او أكثر',
    'Delete': 'حذف',
    'Type your note here': 'أكتب ملاحظتك هنا',
    'Add Note': 'إضافة ملاحظة',
    'Provide valid Email': 'البريد الإلكتروني غير صحيح',
    'Not updated': 'لم يرفع',
    'Saved locally': 'محفوظ',
    'Uploading ...': 'جاري الرفع...',
    'Downloading ...': 'جاري التنزيل...',
    'General Note': 'ملاحظات عامة',
    'Enter general note ....': 'ادخل ملاحظة عامة',
    'disconnected_message':
        '''لست متصل بالإنتارنت كما هو ظاهر ,رجاء‘ تحقق من اتصالك ثم اعد المحاوله.''',
    'network_connection': 'حالة الاتصال بالشبكة',
    'Reload': 'إعادة المحاوله',
    'Continue with offline': 'المتابع بدون اتصال',
    'There is no more requests': 'لم يعد هناك المزيد من الطلبات',
    "It's seems you are logged out, Offline mode is allowed while you are logged in":
        "أنت لست مسجل دخول, وضع عدم الأتصال يحتاج الى تسجبل دخولك",
    'Update': 'تحديث',
    'Skip': 'تخطي',
    'update_message':
        'لقد توفر تحديث جديد للتطبيق إصدار : @newVer ,@isShould تحديثه الأن.',
    'there_update': 'يوجد خبر سعيد',
    'have_to': 'ينبغي',
    'can': 'تستطيع',
    'is_not_enable_to_using_offline_mood':
        "ربما لم تسجل دخولك او أنك لم تحمل البيانات الاساسية لإستخدام وضع عدم الإتصال, رجاء‘ تأكد من إعدادات التطبيق",
    'App Settings': 'إعدادات التطبق',
    'General Settings': 'إعدادات عامة',
    'Offline Mode Settings': 'إعدادات وضع عدم الإتصال',
    'Permission Required': 'صلاحية الوصول مطلوبة',
    'You must to give a permission to can use camera or select image from gallery':
        'ساعدنا للحصول على تصريحك للوصول للكاميرا او البوم الصور الخاص بك من الإعدادات',
    'Go to settings': 'الذهاب للإعدادات',
    'Welcome back': 'لقد كنا بإنتظارك',
    'Remember Me': 'تذكرني',
    'Add OBD code': 'إضافة رمز الOBD',
    'Type OBD code here': 'أدخل رمز الOBD هنا',
    'Searching Code Description...': 'جاري البحث عن الرمز...',
    'Type Code Description': 'أدخل وصف الرمز هنا',
    'Add': 'إضافة',
    'Request Information': 'معلومات الطلب',
    'Inspection Point Results': 'نتائج نقاط الفحص',
    'Point Categories': 'تصنيف النقاط',

    'The file is not PDF, You should to upload PDF file.':
        'الملف الذي حددته ليس من نوع PDF, فضلاً اختار ملف PDF',
    'Edit General Note': 'تحرير ملاحظات عامة',
    'Type General Note for the inspection':
        'أدخل ملاحظاتك العامه على طلب الفحص',
    'Are You Sure?': 'هل تريد الحفظ',
    'Do you want to save all modified values ? Or want to get back without saving any values ?':
        'يوجد معلومات تم التعديل عليها, هل تريد حفظها ؟ يمكنك الخروج دون حفظ المعلومات او الإلغاء.',
    'Save': 'حفظ',
    'Exit': 'لا تحفظ',
    'There is no OBD Code': 'لا يوجد رموز OBD مسجله بعد',
    'EditNumber': 'تعديل رقم الجوال',

    /// Body Notes / Marker Dialog
    FTexts.markerTitle: 'إضافة ملاحظة',
    FTexts.markerInputTitle: 'الملاحظة',
    FTexts.markerInputHint: 'صف المشكلة...',
    FTexts.markerSelectTitle: 'حدد نوع الملاحظة',
    FTexts.markerNoteRequired: 'الملاحظة مطلوبة',
    FTexts.markerNoteRequiredMsg: 'يجب وصف المشكلة',
    FTexts.markerTypeRequired: 'النوع مطلوب',
    FTexts.markerTypeRequiredMsg: 'يجب تحديد نوع الملاحظة',
    FTexts.markerAddPhoto: 'التقاط صورة',
    FTexts.markerChangePhoto: 'تغيير الصورة',
    FTexts.bodyInspectionDetails: 'تفاصيل الفحص',

    /// Body part labels
    FTexts.bodyPartTop: 'أعلى',
    FTexts.bodyPartLeft: 'يسار',
    FTexts.bodyPartRight: 'يمين',
    FTexts.bodyPartFront: 'أمام',
    FTexts.bodyPartBack: 'خلف',
    FTexts.bodyPartInterior: 'داخلي',

    /// Marker success / error
    FTexts.markerSavedSuccess: 'تم الحفظ',
    FTexts.markerSavedSuccessMsg: 'تم حفظ الملاحظة بنجاح',
    FTexts.markerDeletedSuccess: 'تم الحذف',
    FTexts.markerDeletedSuccessMsg: 'تم حذف الملاحظة بنجاح',
    FTexts.markerErrorTitle: 'خطأ',
    FTexts.markerErrorMsg: 'حدث خطأ، يرجى المحاولة مرة أخرى',
    FTexts.systemInspector: 'مفتش النظام',

    /// Inspection Stage Labels
    FTexts.stageAll: 'الكل',
    FTexts.stagePending: 'قيد الانتظار',
    FTexts.stageAccepted: 'مقبول',
    FTexts.stageInfo: 'معلومات المركبة',
    FTexts.stagePoints: 'نقاط الفحص',
    FTexts.stagePhotos: 'الصور',
    FTexts.stageBody: 'ملاحظات الهيكل',
    FTexts.stageObd: 'OBD',
    FTexts.stageFinished: 'منتهي',
    FTexts.stageRejected: 'مرفوض',
    FTexts.stageReviewed: 'معتمد',
  };
}
