import '../constants/text_strings.dart';

class English {
  English._();

  static Map<String, String> en = {
    /// Global Texts
    FTexts.appName: 'Fahis',
    FTexts.cancelBtn: 'Cancel',
    FTexts.skip: 'skip',
    FTexts.refresh: 'Refresh',
    FTexts.submitBtn: 'Submit',
    FTexts.nextBtn: 'Next',
    FTexts.backBtn: 'Back',
    FTexts.requestId: 'Request ID',
    FTexts.deleteBtn: 'Delete',
    FTexts.signOut: 'Sign Out',
    FTexts.updateAssets: 'Assets Upgrade',
    FTexts.offlineMode: 'Offline Mode',
    'All': 'All',
    'sessionExpired': 'Session Expired',
    'sessionExpiredMsg': 'You signed in elsewhere. Please log in again.',
    'fieldRequired': 'This field is required.',
    'vinMustBe17': 'Must be 17 characters.',
    'ccNumbersOnly': 'Only digits allowed.',
    'colorNoNumbers': 'Color cannot contain numbers.',
    'milageNumbersOnly': 'Must be a number.',
    'Pending': 'Pending',
    'Accepted': 'Accepted',
    'In Progress': 'In Progress',
    'Finished': 'Finished',
    'Rejected': 'Rejected',
    'Reviewed': 'Reviewed',
    'Settings & Support': 'Settings & Support',
    'Help & Support': 'Help & Support',
    FTexts.unSelected: 'Not Selected',
    ForgetPage.forgetSubTitle:
        'Enter your mobile number and we will send you a verification code',
    FTexts.more: 'More',

    /// End Global Texts
    ///
    /// Enums Texts
    FTexts.automatic: 'Automatic',
    FTexts.manual: 'Manual',
    FTexts.fabric: 'Fabric',
    FTexts.leather: 'Leather',
    FTexts.inProgress: 'In Progress',
    FTexts.pended: 'Pending',
    FTexts.approved: 'Approved',
    FTexts.finished: 'Finished',
    FTexts.good: 'Good',
    FTexts.notes: 'Note',
    FTexts.na: 'N/A',

    /// End Enums Texts
    ///
    /// Login Page
    LoginPage.loginTitle: 'Inspection Center App',
    LoginPage.loginSubTitle: 'Welcome Back',
    LoginPage.phoneNumber: 'Phone Number',
    LoginPage.phoneNumberValidation: 'Phone Number must be a correct',
    LoginPage.username: 'Email or mobile',
    LoginPage.emailValidation: 'Password must be bigger than 8 characters',
    LoginPage.password: 'Password',
    LoginPage.passwordValidation: 'Password Validation',
    LoginPage.rememberMe: 'Remember me',
    LoginPage.signIn: 'Login',
    LoginPage.verifyOTP: 'Verify',
    LoginPage.resetPassword: 'Reset Password',
    'resetPasswordSubtitle': 'Enter your new password below.',
    'newPassword': 'New Password',
    'confirmPassword': 'Confirm Password',
    'passwordMismatch': 'Passwords do not match',
    LoginPage.forgetBTN: 'Forget password?',
    LoginPage.loginWithEmail: 'Login using email address',
    LoginPage.otpTitle: 'One-Time Password',
    LoginPage.resendBtnWithTime: 'Resend (after @s \'s)',
    LoginPage.resendBtn: 'Resend',
    LoginPage.editPhoneNumber: 'Edit phone number',
    LoginPage.processingTitle: 'Logging in and processing data ...',

    /// End Login Page
    ///
    /// Home Page
    HomePage.searchHint: 'Search for a plate number....',
    HomePage.request: 'Requests',
    HomePage.searchPlaceholder: 'Search...',
    HomePage.history: 'History',
    HomePage.onEmpty: 'There is no request yet',
    HomePage.onError: 'There is an error occurred',
    HomePage.noMore: 'There is no request yet',

    /// End Home Page
    ///
    /// Home Page
    InspectionPage.generalInfo: 'General Information',
    InspectionPage.vehicleInfo: 'Vehicle Information',
    InspectionPage.connectPersonInfo: 'Connect Person Information',
    InspectionPage.inspectionPointReview: 'Inspection Point Review',
    InspectionPage.inspectionType: 'Inspection Type',
    InspectionPage.center: 'Inspection Center',
    InspectionPage.centerBranch: 'Center Branch',
    InspectionPage.city: 'City',
    InspectionPage.bookingDate: 'Booking Date',
    InspectionPage.assignedTo: 'Assigned To',
    InspectionPage.inspector: 'Inspector',
    InspectionPage.inspectedAt: 'Inspected At',
    InspectionPage.reviewedAt: 'Reviewed At',
    InspectionPage.createdAt: 'Created At',
    InspectionPage.inspectorNote: 'Inspector Note',
    InspectionPage.reviewerNote: 'Reviewer Note',
    InspectionPage.notYet: 'Not Set Yet',
    InspectionPage.anyInspector: 'All Inspectors',
    InspectionPage.vin: 'VIN',
    InspectionPage.serialNo: 'Serial No',
    InspectionPage.make: 'Make',
    InspectionPage.model: 'Model',
    InspectionPage.storageSize: 'Storage Size',
    InspectionPage.vehicleShape: 'vehicle Shape',
    InspectionPage.yearModel: 'Year Model',
    InspectionPage.plate: 'Plate',
    InspectionPage.contactName: 'Name',
    InspectionPage.contactEmail: 'Email',
    InspectionPage.contactPhone: 'Phone',
    InspectionPage.contactCity: 'City',
    InspectionPage.inspectionPhotos: 'Inspection Photos',
    InspectionPage.inspectionBodyNotes: 'Inspection Body Notes',
    InspectionPage.inspectionOBDCodes: 'Inspection OBD Codes',
    InspectionPage.loadingInspectionDetails: 'Loading inspection details...',
    InspectionPage.noteLabel: 'Note @index',
    InspectionPage.positionLabel: 'Position: (@dx, @dy)',
    InspectionPage.notesCount: '@count notes',
    InspectionPage.pointsReview: 'Points Review',
    InspectionPage.inspectionDetailsTitle: 'Inspection Details',
    InspectionPage.doneBtn: 'Done',
    InspectionPage.remaining: 'remaining',
    InspectionPage.imageRequired: 'Image Required',
    InspectionPage.imageRequiredMsg:
        'You should document the note with an image that describes the status',
    InspectionPage.noteRequired: 'Note Required',
    InspectionPage.noteRequiredMsg: 'You should describe the status',
    InspectionPage.resetPointsTitle: 'Reset Points',
    InspectionPage.resetPointsContent:
        'Are you sure you want to reset all points? This will delete all changes on the current points.',
    InspectionPage.resetPointsConfirm: 'Reset',
    InspectionPage.selectStatus: 'Select Status',
    InspectionPage.addNoteTitle: 'Add Note',
    InspectionPage.noteSavedSuccessMsg: 'The note has been saved successfully',
    InspectionPage.noteHint: 'Type your note here...',
    InspectionPage.noteFieldLabel: 'Note',
    InspectionPage.noteValidation: 'Note is required',
    InspectionPage.photosTitle: 'Photos',
    InspectionPage.uploadedPhotos: 'Uploaded',
    InspectionPage.availablePhotos: 'Available',
    InspectionPage.photoUploaded: 'Uploaded',
    InspectionPage.addPhoto: 'Add Photo',
    InspectionPage.selectPhotoTitle: 'Select Photo to Capture',
    InspectionPage.noPhotosYet: 'No photos yet',
    InspectionPage.photosProgress: '@uploaded / @total photos',
    InspectionPage.takePhoto: 'Take Photo',
    InspectionPage.deletePhoto: 'Delete Photo',
    InspectionPage.deletePhotoConfirm:
        'Are you sure you want to delete this photo?',
    InspectionPage.photoDeletedSuccess: 'The photo was removed successfully.',
    InspectionPage.deleteAllPhotos: 'Delete All Photos',
    InspectionPage.deleteAllPhotosConfirm:
        'Are you sure? All uploaded photos will be deleted and reset.',
    InspectionPage.deleteAllPhotosSuccess:
        'All photos have been deleted successfully.',
    InspectionPage.deleteObdCode: 'Delete Code',
    InspectionPage.deleteObdCodeConfirm:
        'Are you sure you want to delete this OBD code?',
    InspectionPage.deleteBodyNote: 'Delete Note',
    InspectionPage.deleteBodyNoteConfirm:
        'Are you sure you want to delete this note?',
    InspectionPage.photoCategoryExterior: 'Exterior',
    InspectionPage.photoCategoryInterior: 'Interior',
    InspectionPage.startInspection: 'Start Inspection',
    InspectionPage.generalNoteTitle: 'Submit Inspection',
    InspectionPage.rejectionNoteTitle: 'Reject Inspection',
    InspectionPage.noteOptionalHint: 'Add a note (optional)...',
    InspectionPage.confirmSubmit: 'Confirm',
    InspectionPage.cancelBtn: 'Cancel',
    InspectionPage.submitConfirmSubtitle:
        'Are you sure you want to submit this inspection?',
    InspectionPage.rejectConfirmSubtitle:
        'Are you sure you want to reject this inspection?',
    InspectionPage.addNoteLabel: 'Add Note',
    InspectionPage.optionalTag: 'optional',
    InspectionPage.obdFileName: 'OBD Report',
    InspectionPage.uploadObdReport: 'Upload OBD Report',
    InspectionPage.obdCodesTitle: 'OBD Codes',
    InspectionPage.obdCodeRequired: 'Code Required',
    InspectionPage.obdCodeRequiredMsg: 'Please enter the OBD code',
    InspectionPage.obdDescRequired: 'Description Required',
    InspectionPage.obdDescRequiredMsg: 'Please enter the code description',
    InspectionPage.obdDataRequired: 'OBD Data Required',
    InspectionPage.obdDataRequiredMsg:
        'Please upload a report file or add at least one OBD code before proceeding',
    InspectionPage.obdFileTooLarge: 'File Too Large',
    InspectionPage.obdFileTooLargeMsg: 'File must be less than 10 MB',
    InspectionPage.obdUploadSuccess: 'Report uploaded successfully',
    InspectionPage.obdUploadFailed: 'Failed to upload report',
    InspectionPage.obdDeleteSuccess: 'Report deleted',
    InspectionPage.obdDeleteReportTitle: 'Delete Report',
    InspectionPage.obdDeleteReportConfirm:
        'Are you sure you want to delete the OBD report?',
    InspectionPage.obdCodeDeletedSuccess: 'Code Deleted',
    InspectionPage.obdCodeDeletedSuccessMsg:
        'OBD code has been deleted successfully',
    InspectionPage.obdCodeAddSuccess: 'Code Added',
    InspectionPage.obdCodeAddSuccessMsg: 'OBD code has been added successfully',
    InspectionPage.obdCodeEditSuccess: 'Code Updated',
    InspectionPage.obdCodeEditSuccessMsg:
        'OBD code has been updated successfully',
    InspectionPage.obdActionError: 'Something went wrong, please try again',
    InspectionPage.obdAddCode: 'Add OBD Code',
    InspectionPage.obdEditCode: 'Edit OBD Code',
    InspectionPage.obdCodeLabel: 'OBD Code',
    InspectionPage.obdCodeHint: 'e.g. P0300',
    InspectionPage.obdDescLabel: 'Description',
    InspectionPage.obdDescHint: 'Code description...',
    InspectionPage.obdNoCodesYet: 'No OBD codes yet',
    InspectionPage.bodyNotesEmpty: 'No body notes yet',
    InspectionPage.obdReportSection: 'OBD Report',
    InspectionPage.obdOptionalBadge: 'optional',
    InspectionPage.stepLabel: 'Step @step',
    InspectionPage.submitValidationTitle: 'Cannot Submit',
    InspectionPage.submitValidationMsg:
        'Please complete all steps before submitting:',
    InspectionPage.submitSuccessTitle: 'Submitted',
    InspectionPage.submitSuccessMsg: 'Inspection submitted successfully',
    InspectionPage.stepIncomplete: '@step is incomplete',
    InspectionPage.stepVehicleInfo: 'Vehicle Info',
    InspectionPage.stepPoints: 'Inspection Points',
    InspectionPage.stepPhotos: 'Photos',
    InspectionPage.stepBody: 'Body Notes',
    InspectionPage.stepObd: 'OBD',
    InspectionPage.vehicleInfoRequired: 'Vehicle Info Required',
    InspectionPage.vehicleInfoRequiredMsg:
        'Please fill in all vehicle information fields before proceeding',
    InspectionPage.allPointsRequired: 'All Points Required',
    InspectionPage.allPointsRequiredMsg:
        'Please fill in all inspection points before proceeding',
    InspectionPage.pointsRequired: 'Points Required',
    InspectionPage.pointsRequiredMsg:
        'At least one inspection point must be filled',
    InspectionPage.photosRequired: 'Photos Required',
    InspectionPage.photosRequiredMsg:
        'At least one photo must be uploaded before proceeding',
    InspectionPage.allPhotosRequired: 'All Photos Required',
    InspectionPage.allPhotosRequiredMsg:
        'Please upload all required photos before proceeding',

    /// End Home Page
    ///
    /// Details Page
    DetailsPage.pageTitle: 'Inspection No.@inspection',
    DetailsPage.reviewNoteTitle: 'Review Notes :',
    DetailsPage.vehicleInfoTile: 'Vehicle Information',
    DetailsPage.requestInfoTitle: 'Request Information',
    DetailsPage.inspectionPointResults: 'Inspection Point Results',
    DetailsPage.defaultValidationIfNull: 'The value must be entered',
    DetailsPage.defaultValidation: 'The value must be of 3 characters or more',

    DetailsPage.vin: 'VIN',
    DetailsPage.vinHint: 'Enter VIN',
    DetailsPage.vinValidationIfNull: 'The VIN must be entered',
    DetailsPage.vinValidation: 'The VIN length must be 17',
    DetailsPage.vinSearchBtn: 'Search',
    DetailsPage.vinSearching: 'Searching...',
    DetailsPage.vinFound: 'Vehicle data found',
    DetailsPage.vinFoundMsg: 'Fields have been auto-filled. You can edit them.',
    DetailsPage.vinNotFound: 'Vehicle not found',
    DetailsPage.vinNotFoundMsg:
        'No data for this VIN. You can fill in manually.',
    DetailsPage.vinSearchError: 'Search failed',
    DetailsPage.vinSearchErrorMsg: 'Could not search. Please try again.',
    DetailsPage.vinHelperTyping:
        'Enter 17 characters to search vehicle data automatically',
    DetailsPage.vinHelperReady: 'Tap search to auto-fill vehicle details',
    DetailsPage.sectionIdentification: 'Identification',
    DetailsPage.sectionSpecifications: 'Specifications',
    DetailsPage.sectionInterior: 'Colors & Seating',

    DetailsPage.plateNumber: 'Plate Number',
    DetailsPage.plateNumberHint: 'Enter Plate Number',
    DetailsPage.plateNumberValidationIfNull: 'The Car Plate must be entered',
    DetailsPage.plateNumberValidation:
        'Please complete the plate: 3 letters and 4 digits required',
    'plateLettersLabel': 'Letters',
    'plateNumbersLabel': 'Numbers',
    DetailsPage.bodyType: 'Body Type',
    DetailsPage.bodyTypeValidation: 'Automatic',

    DetailsPage.drivetrain: 'Vehicle Drivetrain',
    DetailsPage.drivetrainValidation: 'Automatic',

    DetailsPage.fuelType: 'Fuel Type',
    DetailsPage.fuelTypeValidation: 'Automatic',

    DetailsPage.gasolineType: 'Gasoline Type',
    DetailsPage.gasolineTypeValidation: 'Automatic',

    DetailsPage.milage: 'Milage',
    DetailsPage.milageHint: 'Enter Milage',
    DetailsPage.milageValidationIfNull: 'The Milage must be entered',
    DetailsPage.milageValidation: 'The Milage must be numbers',

    DetailsPage.yearModel: 'Year Model',
    DetailsPage.yearModelValidation: 'Automatic',

    DetailsPage.exteriorColor: 'Exterior Vehicle Color',
    DetailsPage.exteriorColorHint: 'Select exterior color',
    DetailsPage.exteriorColorValidation: 'Automatic',

    DetailsPage.interiorColor: 'Interior Vehicle Color',
    DetailsPage.interiorColorHint: 'Select interior color',
    DetailsPage.interiorColorValidation: 'Automatic',
    'colorSelectHint': 'Select a color',

    DetailsPage.gearboxType: 'GearBox Type',
    DetailsPage.gearboxTypeValidation: 'Automatic',

    DetailsPage.cylindersNo: 'Cylinders Number',
    DetailsPage.cylindersNoValidation: 'Automatic',

    DetailsPage.engineSize: 'Engine Size CC',
    DetailsPage.engineSizeHint: 'Enter Engine Size (CC)',
    DetailsPage.engineSizeValidationIfNull: 'The Engine Size must be entered',
    DetailsPage.engineSizeValidation:
        'The Engine Size must be normal numbers or decimal',

    DetailsPage.seatType: 'Seat Type',
    DetailsPage.seatTypeValidation: 'Automatic',

    DetailsPage.seatNo: 'Seats Number',
    DetailsPage.seatNoValidation: 'Automatic',

    /// End Details Page
    FTexts.saveBtn: 'Save',
    FTexts.editBtn: 'Edit',
    FTexts.reviewBtn: 'Review Inspection',

    // FTexts.inspectionType: 'Inspection Type',
    //
    // FTexts.inspectionPoints: 'Inspection Points',
    // FTexts.photos: 'Photos',
    // FTexts.vehicleBody: 'Vehicle Body',
    // FTexts.validationTitle: 'Validation',
    // FTexts.validationSubTitle: 'Please ensure your all entries are correct',
    //
    // FTexts.obd: 'OBD',
    // FTexts.defualtSelected: 'Choose One',
    // FTexts.addPhotoBtn: 'Add an additional photo',
    // FTexts.interiorPhotoTitle: 'Interior Photos',
    // FTexts.exteriorPhotoTitle: 'Exterior Photos',
    // FTexts.interiorNotesTitle: 'Interior Notes',
    // FTexts.exteriorNotesTitle: 'Exterior Notes',
    // FTexts.obdCodes: 'OBD Codes',
    // FTexts.desc: 'Description',
    // FTexts.code: 'Code',
    // FTexts.descHint: 'Type description here',
    // FTexts.successfullSavedTitle: 'Successful Saved',
    // FTexts.successfullSavedSubtitle: 'Your inspection results have saved successfully.',
    'The last 6 charts in Car Plate must be numbers':
        'The last 6 charts in Car Plate must be numbers',
    'The First 3 charts in Car Plate must be letters':
        'The First 3 charts in Car Plate must be letters',
    'Type your note here': 'Enter your note here',
    'Add Note': 'Enter Note',
    'Provide valid Email': 'Provide valid Email',
    'Not updated': 'Not updated',
    'Saved locally': 'Saved locally',
    'Uploading ...': 'Uploading ...',
    'Downloading ...': 'Downloading ...',
    'General Note': 'General Note',
    'Enter general note ....': 'Enter general note ....',
    'disconnected_message': '''It seems like no internet connection,
                 Please check from your internet connection and click on reload.''',
    'network_connection': 'Network Connection Status',
    'Continue with offline': 'Continue with offline',
    'Reload': 'Reload',
    'There is no more requests': 'There is no more requests',
    "It's seems you are logged out, Offline mode is allowed while you are logged in":
        "It's seems you are logged out, Offline mode is allowed while you are logged in",
    'Update': 'Update',
    'Skip': 'Skip',
    'update_message':
        'There is a new update Version @newVer, You @isShould update it now.',
    'there_update': 'Good News',
    'have_to': 'have to',
    'can': 'can',
    'is_not_enable_to_using_offline_mood':
        "It's seems you are logged out or the assets are not downloaded, Offline mode is allowed while you are logged in and assets are downloaded",
    'App Settings': 'App Settings',
    'General Settings': 'General Settings',
    'Offline Mode Settings': 'Offline Mode Settings',
    'Permission Required': 'Permission Required',
    'You must to give a permission to can use camera or select image from gallery':
        'You must to give a permission to can use camera or select image from gallery',
    'Go to settings': 'Go to settings',
    'Welcome back': 'Welcome back',
    'Remember Me': 'Remember me',
    'Add OBD code': 'Add OBD code',
    'Type OBD code here': 'Type OBD code here',
    'Searching Code Description...': 'Searching Code Description...',
    'Type Code Description': 'Type Code Description',
    'Add': 'Add',
    'Inspection Point Results': 'Inspection Point Results',
    'Point Categories': 'Point Categories',
    'The file is not PDF, You should to upload PDF file.':
        'The file is not PDF, You should to upload PDF file.',
    'EditNumber': 'Edit phone number',

    /// Body Notes / Marker Dialog
    FTexts.markerTitle: 'Add Note',
    FTexts.markerInputTitle: 'Note',
    FTexts.markerInputHint: 'Describe the issue...',
    FTexts.markerSelectTitle: 'Select Marker Type',
    FTexts.markerNoteRequired: 'Note Required',
    FTexts.markerNoteRequiredMsg: 'Please describe the issue',
    FTexts.markerTypeRequired: 'Type Required',
    FTexts.markerTypeRequiredMsg: 'Please select a marker type',
    FTexts.markerAddPhoto: 'Take Photo',
    FTexts.markerChangePhoto: 'Change Photo',
    FTexts.bodyInspectionDetails: 'Inspection Details',
    FTexts.bodyTapHint: 'Tap to add a marker',
    FTexts.bodyDragHint: 'Drag a marker to reposition',

    /// Body part labels
    FTexts.bodyPartTop: 'Top',
    FTexts.bodyPartLeft: 'Left',
    FTexts.bodyPartRight: 'Right',
    FTexts.bodyPartFront: 'Front',
    FTexts.bodyPartBack: 'Back',
    FTexts.bodyPartInterior: 'Interior',

    /// Marker success / error
    FTexts.markerSavedSuccess: 'Note Saved',
    FTexts.markerSavedSuccessMsg: 'The note has been saved successfully',
    FTexts.markerMovedSuccess: 'Position Updated',
    FTexts.markerMovedSuccessMsg:
        'The note position has been updated successfully',
    FTexts.markerDeletedSuccess: 'Note Deleted',
    FTexts.markerDeletedSuccessMsg: 'The note has been deleted successfully',
    FTexts.markerErrorTitle: 'Error',
    FTexts.markerErrorMsg: 'Something went wrong, please try again',
    FTexts.systemInspector: 'System Inspector',
    FTexts.profileTitle: 'Profile',
    FTexts.logoutBtn: 'Logout',
    FTexts.logoutConfirmTitle: 'Sign Out',
    FTexts.logoutConfirmMessage: 'Are you sure you want to sign out?',
    FTexts.loggingOutTitle: 'Signing out',
    FTexts.loggingOutSubtitle: 'Please wait...',
    FTexts.profileName: 'Name',
    FTexts.profileEmail: 'Email',
    FTexts.profilePhone: 'Phone Number',
    FTexts.profileCity: 'Select City',
    FTexts.profileUpdate: 'Update',
    FTexts.profileNameHint: 'Enter Name',
    FTexts.profileEmailHint: 'Enter Email',
    FTexts.profilePhoneHint: 'Enter Phone Number',
    FTexts.deleteAccountBtn: 'Delete Account',
    FTexts.deleteAccountConfirmTitle: 'Delete Account',
    FTexts.deleteAccountConfirmMessage:
        'Are you sure you want to permanently delete your account? This action cannot be undone.',
    FTexts.deleteAccountError: 'Failed to delete account. Please try again.',
    FTexts.deleteAccountSuccess: 'Your account has been deleted successfully.',

    /// Inspection Stage Labels
    FTexts.stageAll: 'All',
    FTexts.stagePending: 'Pending',
    FTexts.stageAccepted: 'Accepted',
    FTexts.stageInfo: 'Vehicle Info',
    FTexts.stagePoints: 'Inspection Points',
    FTexts.stagePhotos: 'Photos',
    FTexts.stageBody: 'Body Notes',
    FTexts.stageObd: 'OBD',
    FTexts.stageFinished: 'Finished',
    FTexts.stageRejected: 'Rejected',
    FTexts.stageReviewed: 'Approved',
    'Search...': 'Search...',

    /// Home Screen Segments
    'Companies': 'Companies',
    'Individuals': 'Individuals',
    'requests': 'requests',
    'No company requests': 'No company requests',
    'No individual requests': 'No individual requests',
    'No results found': 'No results found',

    /// Notifications Screen
    'Notifications': 'Notifications',
    'No notifications yet': 'No notifications yet',
    'You will see your notifications here':
        'You will see your notifications here',
    'Just now': 'Just now',

    /// Team & Profile
    'Switch Team': 'Switch Team',
    'Teams': 'Teams',
    'Current': 'Current',
    'Team Switched': 'Team Switched',
    'Error': 'Error',
    'Failed to switch team': 'Failed to switch team',
    'Change Photo': 'Change Photo',
    'Camera': 'Camera',
    'Gallery': 'Gallery',
    'Dark Mode': 'Dark Mode',
    'Light Mode': 'Light Mode',
    'No Permission': 'No Permission',
    'Unauthenticated': 'Unauthenticated',
    'No Connection': 'No Connection',
    'Server Error': 'Server Error',
    'Invalid data': 'Invalid data',
    'Not Found': 'Not Found',
    'Unknown Error': 'Unknown Error',

    /// Select Team Screen
    'Select Team to Continue': 'Select Team to Continue',
    'Please select a team to continue using the app':
        'Please select a team to continue using the app',
    'No teams available': 'No teams available',
    'Pull down to refresh': 'Pull down to refresh',

    /// Onboarding
    'getStarted': 'Get Started',
    'onBoardingTitle1': 'Manage Inspections',
    'onBoardingSubTitle1':
        'View and manage all your vehicle inspection requests in one place — easily and efficiently.',
    'onBoardingTitle2': 'Inspect with Precision',
    'onBoardingSubTitle2':
        'Follow step-by-step inspection stages: photos, body check, OBD diagnostics, and more.',
    'onBoardingTitle3': 'Stay Connected',
    'onBoardingSubTitle3':
        'Receive real-time notifications and stay updated on every inspection status change.',

    /// OTP
    'enterOTP': 'Enter Verification Code',
    'otpSentTo': 'OTP has been sent to',
    'otpSending': 'Sending verification code to',
    'otpSentMessage':
        'We sent a verification code to your number. Enter it below.',
    'resendOTP': 'Resend Code',
    'resendIn': 'Resend in ',
    'secondsShort': 's',

    /// Camera
    FTexts.cameraRetake: 'Retake',
    FTexts.cameraUsePhoto: 'Use Photo',
    FTexts.cameraRetry: 'Retry',
    FTexts.cameraOk: 'OK',
    FTexts.imageSourceCamera: 'Camera',
    FTexts.imageSourceGallery: 'Album',
    FTexts.cameraCaptureFailed: 'Failed to capture photo, please try again',
    FTexts.cameraPermissionDeniedTitle: 'Camera Access Denied',
    FTexts.cameraPermissionDenied:
        'Please allow camera access in Settings to continue.',

    /// Force Update
    FTexts.forceUpdateTitle: 'Update Required',
    FTexts.forceUpdateMessage:
        'A new version of the app is available. Please update to continue using the app.',
    FTexts.forceUpdateButton: 'Update Now',

    /// Access Request
    AccessRequestPage.welcomeTitle: 'Welcome to Fahis',
    AccessRequestPage.welcomeSubtitle: 'Choose how you would like to continue',
    AccessRequestPage.alreadyMember: 'Already an inspector',
    AccessRequestPage.requestMembership: 'Apply to become an inspector',
    AccessRequestPage.requestFormTitle: 'Inspector Application',
    AccessRequestPage.fullName: 'Full Name',
    AccessRequestPage.fullNameHint: 'Enter your full name',
    AccessRequestPage.email: 'Email',
    AccessRequestPage.emailHint: 'Enter your email address',
    AccessRequestPage.phone: 'Phone Number',
    AccessRequestPage.phoneHint: 'Enter your phone number',
    AccessRequestPage.city: 'City',
    AccessRequestPage.cityHint: 'Enter your city',
    AccessRequestPage.note: 'Additional Information (optional)',
    AccessRequestPage.noteHint: 'Share any relevant experience',
    AccessRequestPage.submitRequest: 'Submit Application',
    AccessRequestPage.requestSuccessTitle: 'Application Submitted Successfully',
    AccessRequestPage.requestSuccessSubtitle:
        'Your application has been received. Our team will review it and contact you soon.',
    AccessRequestPage.doneBtn: 'Done',
    AccessRequestPage.submissionFailed: 'Submission Failed',
    AccessRequestPage.submissionFailedMsg:
        'Something went wrong. Please try again.',

    /// Paint Gauge
    PaintGaugePage.stepTitle: 'Paint Thickness',
    PaintGaugePage.scanTitle: 'Connect Paint Gauge',
    PaintGaugePage.scanSubtitle:
        'Turn on Bluetooth and place the Guoou device nearby to scan',
    PaintGaugePage.scanButton: 'Scan Devices',
    PaintGaugePage.stopScanButton: 'Stop Scan',
    PaintGaugePage.noDevicesFound: 'No devices found',
    PaintGaugePage.noDevicesSubtitle: 'Tap "Scan Devices" to start',
    PaintGaugePage.scanning: 'Scanning...',
    PaintGaugePage.scanningSubtitle: 'Looking for nearby Bluetooth devices',
    PaintGaugePage.namedDevices: 'Named Devices',
    PaintGaugePage.unnamedDevices: 'Unknown / Unnamed',
    PaintGaugePage.btNotSupported: 'Bluetooth not supported on this device',
    PaintGaugePage.btNotEnabled: 'Please enable Bluetooth',
    PaintGaugePage.btPermissionRequired: 'Bluetooth permissions required',
    PaintGaugePage.skipStep: 'Skip this step',
    PaintGaugePage.connecting: 'Connecting...',
    PaintGaugePage.connected: 'Connected',
    PaintGaugePage.disconnected: 'Disconnected',
    PaintGaugePage.lostConnection: 'Connection lost',
    PaintGaugePage.connectionError: 'Connection error',
    PaintGaugePage.goBack: 'Disconnect',
    PaintGaugePage.connectButton: 'Connect Device',
    PaintGaugePage.connectHint: 'Tap to connect',
    PaintGaugePage.sessionReadingsOnly:
        'Session readings only — no historical data imported',
    PaintGaugePage.measuredPanels: 'Measured',
    PaintGaugePage.noMeasurementYet: 'No measurement yet',
    PaintGaugePage.tapToMoveDevice: 'Tap to move device here',
    PaintGaugePage.readings: 'readings',
    PaintGaugePage.average: 'Average',
    PaintGaugePage.substrate: 'Substrate',
    PaintGaugePage.here: 'HERE',
    PaintGaugePage.clearPanel: 'Clear Panel',
    PaintGaugePage.clearPanelConfirm:
        'This will clear all session readings for this panel.',
    PaintGaugePage.clearAll: 'Clear All Panels',
    PaintGaugePage.clearAllConfirm:
        'This will remove all session readings from every panel.',
    PaintGaugePage.clearSuccess: 'Panel Cleared Successfully',
    PaintGaugePage.clearFailed: 'Failed to clear panel',
    PaintGaugePage.reviewTitle: 'Paint Thickness',
    PaintGaugePage.reviewPanelsMeasured: 'panels measured',
    PaintGaugePage.reviewNoData: 'No measurements recorded',
    PaintGaugePage.panelHood: 'Hood',
    PaintGaugePage.panelRoof: 'Roof',
    PaintGaugePage.panelTrunk: 'Trunk Cover',
    PaintGaugePage.panelLeftFrontFender: 'Left Front Fender',
    PaintGaugePage.panelLeftAPillar: 'Left A-Pillar',
    PaintGaugePage.panelLeftFrontDoor: 'Left Front Door',
    PaintGaugePage.panelLeftBPillar: 'Left B-Pillar',
    PaintGaugePage.panelLeftRearDoor: 'Left Rear Door',
    PaintGaugePage.panelLeftCPillar: 'Left C-Pillar',
    PaintGaugePage.panelLeftRearFender: 'Left Rear Fender',
    PaintGaugePage.panelLeftDPillar: 'Left D-Pillar',
    PaintGaugePage.panelRightDPillar: 'Right D-Pillar',
    PaintGaugePage.panelRightRearFender: 'Right Rear Fender',
    PaintGaugePage.panelRightCPillar: 'Right C-Pillar',
    PaintGaugePage.panelRightRearDoor: 'Right Rear Door',
    PaintGaugePage.panelRightBPillar: 'Right B-Pillar',
    PaintGaugePage.panelRightFrontDoor: 'Right Front Door',
    PaintGaugePage.panelRightAPillar: 'Right A-Pillar',
    PaintGaugePage.panelRightFrontFender: 'Right Front Fender',

    // Offline / sync messages
    'saved_locally_will_sync': 'Saved — will sync when online',
    'offline_bar_message': 'No connection — check your internet',
    'back_online_title': 'Back online',
    'back_online_message': 'Syncing your pending changes…',
    'syncing_offline_changes': 'Syncing offline changes',
    'offline_no_cache_message':
        'This inspection hasn\'t been downloaded yet. Reconnect and pull to refresh.',
    'saved_locally_title': 'Saved locally',
    'saved_locally_message':
        'Will sync automatically when you\'re back online.',
    'queued_delete_title': 'Queued for deletion',
    'queued_delete_message':
        'Will be removed from the server when you\'re back online.',
    'report_not_cached_title': 'Report not available offline',
    'report_not_cached_message':
        'Connect to the internet to load the report for the first time.',
  };
}
