// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeOwl-Srk6IRJYyDtGRTu0R1NL8F-rGow',
    appId: '1:11004766009:web:14d35adcd365a8e1356ae8',
    messagingSenderId: '11004766009',
    projectId: 'fahis-inspector-v1',
    authDomain: 'fahis-inspector-v1.firebaseapp.com',
    storageBucket: 'fahis-inspector-v1.firebasestorage.app',
    measurementId: 'G-2GGPNY66J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARzD4u5sH_Krr99muCIuIDfTkFdYw-hMc',
    appId: '1:11004766009:android:6c4fc28069cf9540356ae8',
    messagingSenderId: '11004766009',
    projectId: 'fahis-inspector-v1',
    storageBucket: 'fahis-inspector-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASh9Hbh9yo8JznDFXf0Rt0HtaE_JlhH_0',
    appId: '1:11004766009:ios:b54cc51e192a646c356ae8',
    messagingSenderId: '11004766009',
    projectId: 'fahis-inspector-v1',
    storageBucket: 'fahis-inspector-v1.firebasestorage.app',
    iosBundleId: 'com.example.fahisInspector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASh9Hbh9yo8JznDFXf0Rt0HtaE_JlhH_0',
    appId: '1:11004766009:ios:b54cc51e192a646c356ae8',
    messagingSenderId: '11004766009',
    projectId: 'fahis-inspector-v1',
    storageBucket: 'fahis-inspector-v1.firebasestorage.app',
    iosBundleId: 'com.example.fahisInspector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeOwl-Srk6IRJYyDtGRTu0R1NL8F-rGow',
    appId: '1:11004766009:web:9f40cde9037ac3d7356ae8',
    messagingSenderId: '11004766009',
    projectId: 'fahis-inspector-v1',
    authDomain: 'fahis-inspector-v1.firebaseapp.com',
    storageBucket: 'fahis-inspector-v1.firebasestorage.app',
    measurementId: 'G-BY45295G1W',
  );

}