// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojhi4w6PPlMOM5rRReMe1sFzQ5Uf1R_E',
    appId: '1:447449059567:web:04a8a581628bb66ff74b1a',
    messagingSenderId: '447449059567',
    projectId: 'fahis-inspector',
    authDomain: 'fahis-inspector.firebaseapp.com',
    storageBucket: 'fahis-inspector.firebasestorage.app',
    measurementId: 'G-M5C414KYW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYkWyS2RGwaET-RklJofZnH0YRN5TVj0',
    appId: '1:447449059567:android:de85da9927cb4db8f74b1a',
    messagingSenderId: '447449059567',
    projectId: 'fahis-inspector',
    storageBucket: 'fahis-inspector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5GixaPntD10KD4wXPs-lJT8GLlI7zIY',
    appId: '1:447449059567:ios:6d3a58f86646e856f74b1a',
    messagingSenderId: '447449059567',
    projectId: 'fahis-inspector',
    storageBucket: 'fahis-inspector.firebasestorage.app',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCojhi4w6PPlMOM5rRReMe1sFzQ5Uf1R_E',
    appId: '1:447449059567:web:21e633b7072fd9f7f74b1a',
    messagingSenderId: '447449059567',
    projectId: 'fahis-inspector',
    authDomain: 'fahis-inspector.firebaseapp.com',
    storageBucket: 'fahis-inspector.firebasestorage.app',
    measurementId: 'G-K1YNZ9GWGP',
  );
}
